### ISSUE TITLE
Research Firebase Authentication for iOS devices

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#108]
### Objective
Look into adding Firebase Authentication for iOS devices.

### Task Description
Firebase Authentication for iOS apps provides a simple way to authenticate users by integrating Firebase's backend services with our SafeRUM iOS development. Implementation would provide our app with user sign-up, user login and session management as well as password reset and email verification services. **The question of whether or not to pay for app registration has been raised.**

### Implementation
A tutorial for setting up our app with Firebase Authentication for Apple Platforms is provided [here](https://firebase.google.com/docs/auth/ios/start). 

### Subtasks
1. Connect SafeRUM to Firebase
2. Add Firebase Authentication to SafeRUM
3. Initialize the Firebase SDK
4. Set up sign-up
5. Set up sign-in

### Testing and Debugging
1. Try registering new users with valid and invalid email/password combinations.
2. Verify login process with correct and incorrect credentials.
3. Request a password reset email and ensure it is delivered.
4. Ensure that user sessions are persistent across app restarts and users remain logged in until they manually log out.
NOTE: Postman is a good tool for testing and debugging APIs, including authentication flows. 

### Deadline
A Firebase authentication connection proposal will be made by Milestone 1. If approved, configuration tasks may extend to Milestone 2.

**Comment by YanehRuiz** [comment]
#139
