### ISSUE TITLE
Design the Report Viewing UI

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#109]
## Objective:

Design the UI for viewing multiple reports and a single report in detail.

## Task Description:

Design the UI for viewing reports. The UI will allow for easy viewing of report at glance and in greater detail.

## Implementation:

The UI will have 2 levels of detail, level 1 with the most important info displayed. Multiple Reports should be displayed by the UI when at the first level of detail 1(similar to a timeline). Level 2 displayed a single report with all the information on hand, level 2 is accessed when selecting a individual report for viewing in greater detail.

## Subtasks:

Designing UI for viewing multiple reports with their most important info displayed
Designing UI for viewing a single report with all it's info displayed

## Deadline:

Milestone 1.

**Comment by jonVargas1** [comment]
Overall Report Viewing:
<img width="289" alt="Screen Shot 2024-09-20 at 5 48 01 PM" src="https://github.com/user-attachments/assets/841f76e6-91a9-4f41-86a4-c247c0142ede">

Individual Report Viewing:
<img width="250" alt="Screen Shot 2024-09-20 at 5 53 15 PM" src="https://github.com/user-attachments/assets/2ec2928e-5a29-4015-a4bf-f0fa027388b9">
