### ISSUE TITLE
Design the "Edit Report" UI 

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#110]
## Objective:

Design the UI for editing existing reports in system.

## Task Description:

Design the UI for editing a report. The UI will allow the process of editing a report only to the original posters and admins. Reports will also show if they were edited. As to allow other users to know where they are seeing the original report or an edited version.

## Implementation:

Reports will have an edit button available only to those who posted the report or admins. Reports must display an edited tag, to notify they were edited from the original version. The edited Report must also display by who the edit was made.

## Subtasks:

Design Report edit button
Design edited Report Tag
Design Report editing Permission

## Deadline:

Milestone 1.

**Comment by diego-velez-upr** [comment]
The difference between this task and #12, that this task is the UI for **editing** the report, while the other task is for **creating** the report.

**Comment by diego-velez-upr** [comment]
The current [report editing UI](https://www.figma.com/design/RkeUIrPmXuTs9OCbmTsNq7/Trust-System-Team?node-id=33-80&t=7fwxb0GK7TfcLMj8-1) is:
![Editing Report UI](https://github.com/user-attachments/assets/e64e841e-45fb-4429-a936-19a607353677)

Each input field will be populated with the report's current respective data, and will allow the responding authorized user to edit said fields, and save the report with the edits made when the edit button is pressed.
