### ISSUE TITLE
Design Report Deletion UI

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#111]
## Objective:

Design UI for Report Deletion

## Task Description:

Design the UI for deleting existing reports. The UI will allow the process of deleting a report, after confirming the intention. Reports can only be deleted by Admins and the Original Posters.

## Implementation:

Reports will have a deletion button, only accesible for the original poster of the report and admins. Admins can deem a report important and disable the deletion function for the original poster if they think having the report visible is of high priority.

## Subtasks:

Design Deletion Button
Design Deletion Permissions

## Deadline:

Milestone 1

**Comment by evnd04** [comment]
Before i close this issue could you please provide the design here as a proof?

**Comment by NathBat09** [comment]
![image](https://github.com/user-attachments/assets/88421fa5-1e7a-4be1-ab2d-c7eaaf5bf8ce)
