### ISSUE TITLE
Implement the report editing UI

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#115]
## Objective
Implement the UI for editing a report

> [!Note]
> This issue depends on the task #110  (Design the report editing UI)

## Task Description
Implement the UI for editing a report. The implementation will follow the design of the report editing system.

## Implementation
Since the system to be will be accepting user input, **it must sanitize/validate said input** in order to ensure that the code is as secure as possible, and minimize the surface area for attacks. The System must make sure that the user editing the report has permission to do so, if the user does not, under no circumstances should the user not be allowed to edit the report. 

## Testing
Unit testing that verifies that the UI was drawn as expected, and that its behavior works as expected should be implemented.
Unit testing must also verify that the edit is successfully reflected in the database.
Unit testing that verifies that the report displayed that is has been edited.

## Deadline
Milestone 1

**Comment by diego-velez-upr** [comment]
PR is up (#293)
