### ISSUE TITLE
Design the "Create Report" UI

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#12]
## Objective
Design the UI for making a report

## Task Description
Design the UI for making a report. The UI will allow the process of creating a report fast and easy for all users. This could be calculated or graded by taking the time it takes from app startup to report creation.

## Implementation
The design will feature an SOS or emergency button for urgent situations, additionally, this button will require user confirmation that will appear after pressing the button.

## Deadline
Milestone 1

**Comment by JorgeRivera94** [comment]
Can be found in discussion #171
