### ISSUE TITLE
Merge Figma Files

### ISSUE THREAD

**Issue by yadrielsamir** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#137]
**Objective:**
-
The objective of this task is to successfully merge all Figma designs into one single file, ensuring that the design elements are consistent with the development framework and align with the project's vision. This task will contribute to a cohesive and user-friendly design experience across all components of the application.

**Task Description:**
-
This task involves integrating the latest Figma designs into a single file. It includes analyzing the current Figma layouts, making adjustments where necessary for compatibility, and ensuring that all design elements such as buttons, colors, and icons align with the codebase. The task will require collaboration between developers to ensure that the aesthetics are fully realized.

**Implementation:**
-
To implement this task, every  individual Figma file will be opened and merged into a single comprehensive file. All screens, components, and assets will be organized systematically. Once consolidated, the final file will be shared with the team for feedback. 

**Testing and Debugging:**
-
Share the merged file with the team for review. Ensure that all assets and designs are correctly placed.

**Deadline:**
-
Milestone 1 - September 20, 2024

**Comment by evnd04** [comment]
Todavia faltan figmas por anadir de los otros team leads no?

**Comment by JorgeRivera94** [comment]
Report Creation:
https://www.figma.com/design/RkeUIrPmXuTs9OCbmTsNq7/Report-Creation?node-id=0-1&t=pllABlsheUK2nsEi-1

**Comment by noel-vargas** [comment]
Login Design: https://www.figma.com/file/XjraecjdkdMNBlDmFyNA32?type=design

Profile Management Page Design: https://www.figma.com/file/VdsIsr8i5rQYLW2SCdzqiL?type=design

Account creation Wireframes:
https://www.figma.com/file/RIkJfzdeSH5rTBQ2MyYYX5?type=design

Forgot Password WireFrames:
https://www.figma.com/file/aBYnEKWsQBzE5VQ5vFf6gG?type=design

UML Design: https://www.figma.com/file/FZj3M6DRT7eLwyIjus00ws?type=design
