### ISSUE TITLE
0.6 Documentation Standards

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#160]
Objective:
To ensure consistency in the format, style, and structure of all project documentation, making it easy to navigate and understand for all team members.

Task Description:
Create a set of standards for writing and organizing documentation. This includes guidelines for formatting, tone, headings, versioning, and file organization. The goal is to provide a uniform structure across all documents to maintain professionalism and coherence.

Implementation:

	•	Research effective documentation formats (Markdown, Wiki, etc.).
	•	Decide on a style guide (e.g., tone, technical terms, use of abbreviations).
	•	Outline how to title and structure sections and subsections within the documents.
	•	Specify how and where documentation files should be stored.

Subtasks:

	1.	Create a basic style guide for writing documentation (headings, tone, etc.).
	2.	Define a file structure and naming conventions for documents.
	3.	Ensure all contributors know where to access and follow the documentation standards.

Testing and Debugging:

	•	Ensure a few team members write documentation using the standards and give feedback.
	•	Check the consistency of new documents across the project and make necessary adjustments to the guidelines.

Deadline:
Wednesday, September 18 at 11:59 PM.

**Comment by misaelmercado1** [comment]
[Documentation guidelines.docx](https://github.com/user-attachments/files/17067526/Documentation.guidelines.docx)

**Comment by lex939** [comment]
Hello, please place all relevant text and media for this documentation issue in the Google Document for the proposal of Milestone 1 so the managers can evaluate it for closing. Remember to follow the flow of the rest of the formatting set by the document to help keep things organized. Thank you.

**Comment by misaelmercado1** [comment]
> Hello, please place all relevant text and media for this documentation issue in the Google Document for the proposal of Milestone 1 so the managers can evaluate it for closing. Remember to follow the flow of the rest of the formatting set by the document to help keep things organized. Thank you.

I thought this was a standalone document do i put it in the google doc?

**Comment by misaelmercado1** [comment]
Added to documentation

**Comment by evnd04** [comment]
Add this to the table of contents before we close
