### ISSUE TITLE
0.7 Project Member Access and Control

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#161]
Objective:
To define clear access levels and roles for each team member involved in the SafeRUM project, ensuring smooth collaboration while protecting sensitive project contents. This system will safeguard important information by limiting access based on role while fostering efficient collaboration.

Task Description:
Establish and document access control for the SafeRUM project by differentiating between roles such as Admin, Maintainer, Developer (Collaborator), and various team positions. Roles and access levels will follow a hierarchical structure, from Managers (highest) to Developers and Hybrids (lowest), with permissions granted accordingly. While the project is collaborative, there will be moments where certain tasks or information are restricted to specific roles such as Team Leaders and above or Documentation Leaders and above.

Implementation:

	•	Define project roles (Admin, Maintainer, Developer, etc.) and assign permissions based on each role.
	•	Set up a hierarchy of access based on team responsibilities, with Managers having the highest permissions and Developers/Hybrids having limited access.
	•	Develop guidelines for when sensitive information or project content can only be accessed by specific groups (e.g., Team Leaders and above, Documentation Leaders and above).
	•	Ensure that the permissions are enforced within the project’s tools (e.g., GitHub, project management platforms).

Roles and Responsibilities:

	1.	Admin:
	•	Full control over all aspects of the project. Can manage repositories, add/remove team members, change project settings, and review and merge code.
	•	Usually held by Managers in the SafeRUM project. Admins have the highest level of access and can intervene in any part of the project.
	2.	Maintainer:
	•	Can manage project repositories, review and merge pull requests, assign tasks, and moderate discussions. Maintainers play a critical role in keeping the project organized and updated.
	•	Typically held by Team Leaders and Documentation Leaders. They have significant control over project content but may not have full admin privileges, especially regarding user management or altering critical project settings.
	3.	Developer (Collaborator):
	•	Has access to work on their assigned parts of the project, create branches, submit pull requests, and collaborate with other developers. Developers primarily focus on feature implementation and bug fixing.
	•	This role is filled by Developers and Hybrids. Their access is limited to the areas they are working on, and they rely on Team Leaders or Maintainers for code reviews and merging into the main project.

Subtasks:

	1.	Define and document the role-based access control structure for all team members.
	2.	Implement permission levels in the project management and code repository tools (e.g., GitHub).
	3.	Establish procedures for handling tasks that are limited to certain roles (e.g., only Documentation Leaders can approve documentation changes).
	4.	Communicate these access rules clearly to all team members, ensuring they understand their permissions and responsibilities.

Testing and Debugging:

	•	Test the access control by assigning roles to sample users and verifying their permissions match the desired levels.
	•	Review feedback from team members to identify any potential issues or gaps in the access hierarchy.
	•	Adjust access levels if necessary to ensure both security and smooth collaboration.

Deadline:
Wednesday, September 18 at 11:59 PM.

**Comment by lex939** [comment]
Hello, please remember to place all relevant text and media for this documentation issue in the Google Document for the proposal of Milestone 1 so the managers can evaluate it for closing. Remember to follow the flow of the rest of the formatting set by the document to help keep things organized. Thank you.

**Comment by misaelmercado1** [comment]
added to documentation

**Comment by evnd04** [comment]
Add this to the table of contents before we close
