### ISSUE TITLE
Add User Authentication Team Update Slide to Milestone 1 Presentation

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#162]
### Objective
User authentication team description included in milestone 1 project presentation. 

### Task Description
Describe the team's objectives and accomplishments during SafeRUM's milestone 1 for our project's presentation. 

### Implementation
Edit [the user authentication slide ](https://www.canva.com/design/DAGQxi1NY9M/KVMrnk9FCPJixHQOgD53iQ/edit?ui=eyJEIjp7IlQiOnsiQSI6IlBCSFMyVlY2RDh6Z1dtNEIifX19) on the project's Canva presentation. 

### Subtasks
- List the team members.
- Name team leader.
- Recap team objectives.
- Summarize team accomplishments for milestone 1. 

### Testing and Debugging
The user authentication team's slide will be reviewed and approved by the managers (@YanehRuiz & @evnd04) as well as our documentation leader (@lex939). 

### Deadline
The user authentication team's slide will be completed and reviewed by Thursday, September 19th.

**Comment by evnd04** [comment]
Whenever possible, add the designs to the presentation, and any implementations done. Try to make the designs readable not too small.
