### ISSUE TITLE
Add Admin Account Team Update Slide to Milestone 1 Presentation

### ISSUE THREAD

**Issue by javier-rivera8** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#164]
Objective
Admin Account team description included in milestone 1 project presentation.

Task Description
Describe the team's objectives and accomplishments during SafeRUM's milestone 1 for our project's presentation.

Implementation
Edit the admin account creation slide on the project's Canva presentation.

Subtasks
List the team members.
Name team leader.
Recap team objectives.
Summarize team accomplishments for milestone 1.

Deadline
The admin account team's slide will be completed and reviewed by Thursday, September 19th.

**Comment by evnd04** [comment]
Add implementation proof in the presentation, screenshots of features and figma designs.
