### ISSUE TITLE
Add 2.4 Validation and Verification

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#169]
Objective:
Ensure that the project’s requirements are validated and accurately reflect the needs of stakeholders and users. This involves confirming that the requirements meet the domain needs and that stakeholders agree on their relevance and completeness. Validation helps ensure that the developed system will meet expectations and fulfill its intended purpose.

Task Description:
The Validation and Requirements section focuses on verifying that the project’s requirements (domain, functional, and technical) are aligned with the expectations of users, stakeholders, and the broader domain. Validation involves reviewing and discussing the requirements with stakeholders to ensure they are complete, unambiguous, and feasible. This task ensures that all requirements are grounded in stakeholder needs and that any gaps or misunderstandings are identified early.

Implementation:
1. Review the documented requirements (domain, functional, technical) and identify areas that need stakeholder validation.
2. Plan and conduct validation activities, such as walkthroughs, stakeholder reviews, and requirement confirmation sessions.
3. Document any feedback, clarifications, or updates needed based on the validation process.
4. Refine and update the requirements as necessary to reflect the validated feedback, ensuring alignment with project goals and stakeholder expectations.

Subtasks:
• Requirement Review: Perform an internal review of all documented requirements to ensure they are clear, unambiguous, and complete.
• Stakeholder Validation: Schedule and conduct meetings with stakeholders to validate the requirements, ensuring they meet stakeholder needs and expectations.
• Feedback Documentation: Capture stakeholder feedback, identifying areas where requirements may need adjustment, clarification, or additional detail.
• Refinement: Update the requirements documentation based on the feedback gathered during validation, ensuring all issues or concerns are addressed.
• Final Validation: Perform a final round of validation to confirm that the refined requirements are agreed upon and meet all project goals.

Testing and Debugging:
• Review the feedback from validation sessions with the team to ensure it has been correctly incorporated into the requirements.
• Ensure that any ambiguous or conflicting requirements are resolved and agreed upon by all stakeholders.
• Validate that all changes and updates to the requirements maintain consistency with the overall project scope and domain needs.

Deadline:
Wednesday, September 30 at 11:59 p.m.

**Comment by CaribbeanCool** [comment]
@lex939 I finished this part + added the green highlight and added it to the table of contents
