### ISSUE TITLE
Designing an Alert System to Receive Specific Alerts (SOS, Panic Alert, Immediate Help)

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#179]
## Objective:

Design a robust alert system capable of receiving and distinguishing between specific types of alerts (SOS, Panic Alert, Immediate Help) to ensure quick and appropriate responses to emergency situations.

## Task Description:

The task involves designing the user interface and functionality of an alert system that allows users to send and receive different types of alerts. These alerts—SOS, Panic, and Immediate Help—must be visually distinct and easily recognizable. The system will also need to categorize and prioritize these alerts, ensuring the most urgent alerts are immediately flagged for action.

## Implementation:

Research existing alert systems to gather design inspiration and best practices.
Design user interface components that clearly distinguish between the types of alerts, including different colors, icons, and labels.
Create wireframes or mockups of how the alerts will appear on various platforms (desktop, mobile, etc.).
Ensure accessibility considerations, such as sound and visual cues, are included for users with disabilities.
Collaborate with the development team to ensure the design aligns with backend functionality and performance requirements.
### Research & Analysis:

Research existing emergency alert systems and identify key features.
Define the visual and functional requirements for each type of alert (e.g., colors, icons, urgency levels).
### Designing the User Interface:

Create wireframes and mockups for the alert system.
Design visual elements (icons, buttons) for SOS, Panic, and Immediate Help alerts.
Design different alert levels and how they will be presented on various screens (desktop, mobile).
### User Interaction Flow:

Design the user interaction flow for sending and receiving alerts, ensuring a seamless experience.
Design notification behaviors, such as pop-ups, sound, and vibration for urgent alerts.
### Collaboration with Development Team:

Review designs with developers for feasibility and adjustments.
Ensure design consistency with the overall system and compatibility across platforms.
# ## Testing and Debugging:

Test the alert designs with different user groups to ensure clarity and ease of use.
Conduct accessibility testing, including colorblind-friendly design, sound volume, and visual cues.
Perform user acceptance testing to ensure that users can easily differentiate between alert types.
## Deadline:

Milestone # 2

**Comment by evnd04** [comment]
Same question as #180
