### ISSUE TITLE
Implementing the Alert Designs into the Pages

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#180]
## Objective:

To integrate the newly designed alert system (SOS, Panic Alert, Immediate Help) into the relevant pages of the application, ensuring functionality and ease of use for end users.

## Task Description:

This task involves taking the previously designed alerts (SOS, Panic, Immediate Help) and implementing them across the application. The goal is to ensure that these alerts can be triggered and displayed effectively on the user interface, while also being logged or sent to the appropriate responders if needed. This includes both the front-end implementation of the alerts and their proper integration with backend systems for handling and prioritization.

## Implementation:

Implement the designed alerts (SOS, Panic, Immediate Help) into the appropriate pages of the application.
Ensure that each type of alert triggers the correct response, such as notifications, logs, and communication with external systems or responders.
Integrate real-time feedback for users when they send an alert (e.g., confirmation messages, visual cues).
Implement sound, vibration, and pop-up notifications based on the urgency of the alert.
Coordinate with the backend team to ensure that alert data is stored and handled properly, including escalation protocols for higher-priority alerts.
### Front-end Integration:

Implement the visual elements (buttons, icons) and interactions for sending alerts on the user interface.
Embed the alerts into the relevant sections/pages of the application.
Ensure alerts are responsive and display correctly on all screen sizes (desktop, mobile).
### Backend Integration:

Work with backend developers to ensure the alerts trigger the correct system responses (e.g., sending notifications, logging).
Implement real-time alert data transmission for live updates to users or responders.
### User Feedback & Notifications:

Implement visual and auditory feedback for users upon sending alerts (e.g., confirmation pop-ups, sound, or vibration based on alert type).
Ensure that users are informed when their alert has been received and handled by the system.
### Testing:

Test alert functionality across all pages to ensure they trigger correctly and are displayed consistently.
Perform load testing to ensure the system can handle multiple alerts without performance degradation.
### Documentation:

Document the alert implementation process and how to manage the system for future maintenance or updates.
### Testing and Debugging:

Test alert interactions across different user devices and platforms.
Conduct unit and integration testing for seamless backend and frontend communication.
Perform stress tests to ensure the system can handle high-volume alert traffic.
Ensure real-time feedback works under various network conditions (online/offline scenarios).
## Deadline:

Milestone # 2

**Comment by evnd04** [comment]
Would there be a need for SOS, Panic, Immediate Help if an SOS button is already implemented? If is the case only one button should be made since SOS should cover all emergency circumstances.
