### ISSUE TITLE
Designing the Help Button for Emergency Situations

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#181]
## Objective:

Design a user-friendly and highly visible help button that users can easily access during emergency situations to quickly send an alert, ensuring swift and appropriate action.

## Task Description:

The task involves designing a help button that users can use to send alerts in case of emergencies. The button needs to be highly accessible, visually distinct, and intuitive for immediate use under stress. The design should also account for different devices and platforms (desktop, mobile), ensuring it is always within easy reach. The button should clearly convey its purpose (e.g., "SOS", "Help", "Emergency") and integrate well with the existing user interface without being intrusive during regular usage.

## Implementation:

Research user-friendly emergency buttons in apps and websites for inspiration.
Design a prominent and recognizable button with clear text or icons (e.g., a red emergency button with an SOS or Help icon).
Ensure that the button is large enough for quick use on both desktop and mobile, with responsive design elements.
Provide options for button placement (e.g., sticky button on the side or bottom corner of the screen) to ensure it’s always accessible.
Incorporate accessibility features like text labels, color contrast, and tactile feedback (for mobile devices) to ensure usability for all users.
Collaborate with the development team to ensure the button functions properly and triggers the correct alert process when pressed.
### Research & Analysis:

Research other emergency systems and buttons for design inspiration and best practices.
Identify critical features that make emergency buttons easy to find and use.
### Button Design:

Create initial mockups of the button design, focusing on high visibility, color contrast, and iconography.
Design several variations (size, icon, color) for different platforms and screen sizes (desktop, mobile).
Design how the button will behave when pressed (e.g., color change, sound, vibration on mobile).
### User Interaction Flow:

Design the interaction flow when a user presses the help button, including confirmation prompts (e.g., “Are you sure?”) or immediate feedback (e.g., “Help alert sent”).
Ensure the flow is intuitive and stress-free, requiring minimal steps to send an emergency alert.
### Collaborate with Development Team:

Review button designs with developers to ensure technical feasibility.
Coordinate to integrate the button with the backend system for sending and receiving alerts.
### Testing and Debugging:

Conduct usability testing to ensure the button is easily visible and accessible across different devices and environments.
Test the responsiveness and behavior of the button under different scenarios (e.g., during app usage, idle, online/offline).
Conduct accessibility testing to ensure it works for users with disabilities (colorblind, visually impaired, etc.).
Perform security testing to ensure the button is not easily triggered by mistake but remains accessible when needed.
## Deadline:

Milestone # 2

**Comment by evnd04** [comment]
Isnt there a SOS button already?

**Comment by YanehRuiz** [comment]
> I have not seen one, but I though there was going to be more than an SOS button, like one button for police emergencies, another for medical emergencies and more. Or should we just keep it as an SOS?

It would be more convenient to have a single button that performs all actions. This would simplify the user experience, especially in an emergency situation where they may not have time to choose who to reach out to.
