### ISSUE TITLE
Create Detailed Workflow Diagrams for User signUp/Login/ViewReport

### ISSUE THREAD

**Issue by noel-vargas** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#201]
Objective:

To develop comprehensive workflow diagrams that visually represent the data flow, component interactions, and user interactions within the application's key components, including the login screen, sign-up screen, and report viewing/editing modal.

Task Description:

This task involves creating detailed diagrams that illustrate how data moves through the application's components. The diagrams will focus on user login, user sign-up, and report viewing/editing functionalities. The goal is to enhance understanding of the application's architecture, facilitate team communication, and identify potential areas for optimization or improvement.

Implementation:

Utilize diagramming tools to create the diagrams. Base the diagrams on the code analysis, ensuring accuracy in representing components, state variables, functions, user interactions, and data flows.
Incorporate various types of diagrams as appropriate, such as flowcharts, sequence diagrams, data flow diagrams, and component diagrams.
Ensure that the diagrams are clear, well-organized, and accessible to all team members.
Subtasks:

* Login Screen Workflow Diagram:

Illustrate the user authentication process, including input validation, Firebase authentication interactions, and error handling mechanisms.
Highlight state changes and data flow between the user interface and authentication services.

* Sign-Up Screen Workflow Diagram:

Depict the user registration flow, focusing on data collection, input validation, password handling, and potential backend integration points.
Show how user inputs are processed and stored.

* Report Viewing/Editing Modal Diagram:

Create a diagram demonstrating how the modal handles viewing and editing reports, including state management for edit mode and data binding between UI components and data models.
Outline the flow for toggling between view and edit modes and saving changes.

* Integrated Application Workflow Diagram:

Combine the individual component diagrams to present an overall workflow of the application.
Show how different components interact and how data flows throughout the application.
Testing and Debugging:

Deadline: October 25, 2024

**Comment by evnd04** [comment]
When working wi†h the password, its preferable that its not displayed outright, if possible display only dots, when pressed you confirm the password and then it displays the password without hiding. Just for security. You could connect this to the change your password feature also just in case a user doesnt remember their password.

**Comment by noel-vargas** [comment]
Someone mistakenly did my task so I'll be changing the task description.

**Comment by noel-vargas** [comment]
Sign Up: 
![image](https://github.com/user-attachments/assets/83cc7296-42fb-4c0b-8603-5045ded1f72b)
ViewReport:
![image](https://github.com/user-attachments/assets/462ad7d3-a07f-41fe-88d8-a88760dfd748)
Login:
![image](https://github.com/user-attachments/assets/570f2b5d-f182-4bf9-b63c-d5fb4d0f08c3)
