### ISSUE TITLE
Design the admin's communication interface in Figma

### ISSUE THREAD

**Issue by Chosen-Juan1** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#203]
Objective: Implement admin's communication interface in Figma before carrying out a full implementation in code to make sure the page acts the way we want it to.

Provide an objective for the task (What would the task accomplish if implemented?):
The objective shall be done once the page is made in Figma

Task Description:

Using the designed posted in issue #49, the admin's communication interface shall be designed in Figma to see if it viable prior to being implemented with code.

Implementation:

Provide implementation ideas on how you would implement the feature, this could be added on with time as you work on the feature.

Subtasks: N/A

Testing and Debugging:

It will be debugged by being presented to the admin team to see if all approve of it's looks and functionality.

Deadline: ~Monday, 30th of September

Suggested score: difficulty = 3
urgency = 5
3 * 5 = 15

**Comment by YanehRuiz** [comment]
Please ensure the design remains as cohesive as the others

**Comment by Chosen-Juan1** [comment]
Finished the design, here is the link (https://www.figma.com/design/USGPEXPHcFUy91OeGu5uGY/SafeRum-admin-interface?node-id=0-1&t=QsrBNDJsHnwWdqBI-1)
<img width="601" alt="Screenshot 2024-10-15 at 9 07 55 PM" src="https://github.com/user-attachments/assets/7eda386c-f61a-464f-a78e-2ae5984ae005">

**Comment by evnd04** [comment]
Looks good id say make the Report title bolded and maybe a bit smaller so you can make the description a bit more legible.

**Comment by Chosen-Juan1** [comment]
<img width="399" alt="Screenshot 2024-10-16 at 5 30 27 PM" src="https://github.com/user-attachments/assets/ae5f1596-9801-4ef7-8d38-0d7dc73259d4">

is this better? @evnd04

**Comment by evnd04** [comment]
Thats good, The report title a small bit bigger, Ill close the issue thought thank u!
