### ISSUE TITLE
Create the design for a button that displays a list of reported locations

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#205]
##  Objective:
  
  Provide a way for the user to look at a list of all markers in map
  
 ## Task Description:
  
  Create the design for a button in the Report Map page that, when pressed, displays an overlay showing all the locations that can be marked. User should be able to scroll to see all the locations, and the amount of reports for that given location.
  
 ## It's important to note that each location needs to be mapped to a building
  
  
 ## Implementation:
  
  Utilize Figma for the Mock Ups.
  
 ## Subtasks:
  
  - Create Design for the new Button
  - Create Overlay of the list of markers
  
  ## Testing and Debugging:
  
  Not Needed
  
 ## Deadline:
  
  Milestone 2

**Comment by misaelmercado1** [comment]
![image](https://github.com/user-attachments/assets/3c51fa4e-a932-4de2-8a63-08b35d087285)
Here is the design i added the report text as a placeholder since we do not know what the name of the button is going to be . i included a screenshot here but the actual button is located in figma
