### ISSUE TITLE
Script to Download Closed Issues from GitHub and Save them in a Word Document

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#206]
### Objective
Closed issues from a specific GitHub milestone will be retrieved and stored in a Word document using a Python script.

### Task Description
Downloading and organizing closed issues is essential to track the progress of milestones effectively. This task involves implementing a script that uses the GitHub API to fetch all closed issues from a specific milestone and save them in a Word document (.docx). Each issue should include the title, contributor’s username, and email (if available). Pull requests should be excluded from the results. The solution must handle pagination to ensure all issues are downloaded.

### Implementation

- Use Python to implement the script, leveraging libraries such as requests for API calls and python-docx to create the Word document.

- Use a personal token for authentication with the GitHub API to avoid rate limits.

- The script should handle pagination to download all closed issues, as GitHub only returns 30 results per page.

- Filter out pull requests to ensure only issues are included.

- Implement logic to fetch contributors' emails, either from their user profile or recent commits in the repository.

- Save the results in a Word document with a table containing:
Issue title
Contributor’s username
Contributor’s email (or a fallback message if unavailable)

### Subtasks
Select API and Tools:

- Use the GitHub API with requests for fetching data.

- Use python-docx to generate the Word document.

- Implement the API Call:

- Authenticate with a personal GitHub token.

- Fetch closed issues for a specific milestone.

- Handle pagination to retrieve all issues.

- Exclude pull requests from the results.

- Retrieve Emails:

- Try to get the email from the contributor’s profile.
If the profile email is unavailable, attempt to extract it from their recent commits in the repository.

- Create the Word Document:

Save the results in a .docx file with a table including the following columns:
Issue Title
Contributor
Email

### Testing and Debugging

- Verify that all closed issues are fetched for the selected milestone, including handling pagination.
- Ensure pull requests are excluded from the results.
- Test email retrieval:
- Confirm that contributor emails are shown when available.
- Display "No email available" when the email is not accessible.
- Visual Check:
- Open the generated Word document and confirm the formatting and structure of the table.
- Edge Case Testing:
- Verify the script handles milestones with no issues or more than 30 issues.
- Ensure that long issue titles or missing emails do not break the document layout.

### Deadline
This issue should be resolved by the end of the second milestone on October 25th, 2024.

**Comment by YanehRuiz** [comment]
This issue will be closed but not merged until the runtime error issue is completed!
