### ISSUE TITLE
Implement Button for displaying list of report locations

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#207]
## Objective:

Provide a way for the user to look at a list of all markers in map

## Task Description:

Create a button in the Report Map page that, when pressed, displays an overlay showing all the locations that can be marked. User should be able to scroll to see all the locations, and the amount of reports for that given location.

It's important to note that each location needs to be mapped to a building

## Implementation:

Use the React Native Maps Library to implement this feature

## Subtasks:

- Implement the button
- Implement Overlay displayed on button tap
- Add every location on the list. If there are no reports for the location, it should appear as having "0" reports

## Testing and Debugging:

Test locally

## Deadline:

Milestone 2

**Comment by misaelmercado1** [comment]
Heres is the pull request for this task https://github.com/uprm-inso4116-2024-2025-s1/semester-project-SafeRUM/pull/315

**Comment by YanehRuiz** [comment]
Remember to associate the pull requests with their corresponding issues and mark them as closed ^^
