### ISSUE TITLE
Add Custom Callouts to the Report Map Pins

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#208]
Objective:

Provide additional information for pinned locations on the report map.

Task Description:

Implement a custom callout when hovering over and tapping on a pinned location. Callout should contain the following:

- Name of Location
- Amount of reports
- Highest Danger Level

Implementation:

Utilize the React Native Maps library to implement this feature.

Subtasks:

- Add the custom callout for every pin
- Add the needed information for each callout

Testing and Debugging:

Can be tested locally, but a new issue can be added for unit testing.

Deadline:

Milestone #2

**Comment by CaribbeanCool** [comment]
@Jjulianirizarry24 For this task, how many pins should be placed? or do I just place some placeholder pins?
