### ISSUE TITLE
Create Mockup for User Status Icon

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#209]
## Objective:

Create a Visual Aid to check how close user is to danger.

## Task Description:

Create a design in figma indicating user status depending on how close user is to risky incidents

## Implementation:

Create design in Figma

## Subtasks:

Create design for the status with three states: Safe, Uneasy, Unsafe

## Testing and Debugging:

Not needed 

## Deadline:

Milestone 2

**Comment by evnd04** [comment]
Would this be a user input or would it be based on the systems location?

**Comment by Jjulianirizarry24** [comment]
https://www.figma.com/design/5x0nt0zD2j2TovQaWvap4r/SafeRum-UI?node-id=0-1&node-type=canvas&t=Acdv1cPD1C6GSqcX-0
