### ISSUE TITLE
 Improve Dummy Data

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#214]
Objective: Improve the current dummy data for reports in the database

Task Description: 
replace the current dummy data in the database as it lacks fields and poorly simulates actual reports, and add new dummy data, with complete reports, to test all fields in the report table. 

Implementation:
Add Dummy Reports into the database,
Dummy Reports must contain: Title, Description, Date, Category of Reports, Users who posted the report, report id, Location.

Testing and Debugging:
Unit tests to check with data fetching
Perform a visual examination of the database.
Debug any issues with data display, such as missing or incorrect information.

Deadline:
Sprint 1 of Milestone 2

**Comment by diego-velez-upr** [comment]
This issue should be completed with PR #288.

**Comment by evnd04** [comment]
When the PR is merged ill close this issue.
