### ISSUE TITLE
Add Reports Tab

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#215]
Objective: 
Add a tab for viewing reports independently from the map.

Task Description: 
Create a separate tab in the interface for users to view reports without needing to interact with or use the map feature. 

Implementation:
Add a new "Reports" tab in the navigation bar.
Add an Icon for the Reports tab in the navigation bar.

Testing and Debugging:
Manual testing of tab navigation and data loading.
Ensure smooth interaction between different parts of the app when switching between tabs.

Deadline:
Sprint 1 of Milestone 2

**Comment by YanehRuiz** [comment]
@MarkoSchuetz This is the issue that was brought up in class by @Alejandro-DeJesus

**Comment by YanehRuiz** [comment]
As per the milestone ending, I am re-closing this issue. Please refer to the last comment for further information.
