### ISSUE TITLE
Create a Set of Report Usage Guidelines

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#217]
Objective:
Create a set of guidelines of how reports should be used, focusing on integrity and Responsibility with the Report Usage.

Task Description:
Create a set of guidelines of how reports should be used, focusing on integrity and Responsibility with the Report Usage. These guidelines will be presented to every user who wishes to make a report.

Implementation:

- Write the rules and guidelines for Report Usage.
- The Rules must contain the reasons a user could be banned from reporting.
- The Rules must mention the ground for your report being removed.
- The Rules must contain examples of proper report usage.
- The Rules must mention what to expect to happen once a report is sent
- The Rules must mention how a user should interact with the reports of others.
- Add an interface for viewing the Rules and Guidelines if the user so wishes.
- Add an interface for presenting the Rules and Guidelines to the user, for creating reports, (only the first time).

Testing and Debugging:

- Perform manual testing across different devices and browsers to check for layout responsiveness and usability.
- Debug any issues with data display, such as missing or incorrect information.

Deadline:
Milestone 2

**Comment by diego-velez-upr** [comment]
This task can be split into 2 subtasks, one which is documentation specific, and the other that is implementation specific. Since we are at the final week of the milestone, I think that we could establish the guidelines for this milestone, then implement them to the project in the next milestone.

I wrote the report usage guidelines in a separate document [here](https://docs.google.com/document/d/1TMjXeD8ezho0sNdMUSZ28O_aF4ALiWb7GjATx1WV6ns/edit?usp=sharing).

**Comment by diego-velez-upr** [comment]
If we do split it into documentation and implementation, I think that we could split it into:

- Design the UI for viewing the rules and guidelines
- Implement the viewing the rules and guidelines feature
- Design the UI for notifying first time reporters of the rules and guidelines
- Implement notifying first time reporters of the rules and guidelines

**Comment by diego-velez-upr** [comment]
Could we split this task?

**Comment by YanehRuiz** [comment]
> Could we split this task?

Yes, you may split this issue!

**Comment by diego-velez-upr** [comment]
Task was split, and implementation tasks were created (#295, #296, #297 and #298). This task should complete the documentation part of the original task. The report usage guidelines created were mentioned in my previous comment. I am requesting a review of the rules and guidelines created to ensure that they successfully complete the documentation part of the task. @YanehRuiz

**Comment by YanehRuiz** [comment]
Looks good to me! I'll tag @lex939 since this is also a documentation issue ^^

**Comment by lex939** [comment]
This should go as part of 4.3

**Comment by diego-velez-upr** [comment]
@lex939 added to documentation as 4.3.2
