### ISSUE TITLE
Creating and Adding the Images for the Status for Help Button and complete its descriptions

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#241]
Objective:
Create and Add the Design Image of Status for safe, danger and caution zones for the Help button.

Task Description:
Create and add the design in figma indicating user status and change the help button and its descriptions

Implementation:
Create design in Figma and Add Code

Subtasks:
Create design for the status with three states: Safe, Uneasy, Unsafe for the Help Button and The fill up the descriptions

Testing and Debugging:
Not needed

Deadline:
Milestone 2

**Comment by Jjulianirizarry24** [comment]
Discussed offline. Issue was reopened and pending for approval/completion
