### ISSUE TITLE
[Lecture Topic Task] Refactoring for Deeper Insight

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#253]
# For the following Lecture Topic: Refactoring for Deeper Insight:
Incorporates new domain knowledge and clarifies the model's expression.
Helps developers understand what the code does and why.
Leads to a breakthrough in understanding and design.

## Objective:

Make code easier to understand.

## Task Description:

Refactor code to help developers in the Location Management Team better understand the base code allowing for easier future implementation and better overall understanding of the project.

## Implementation / Subtasks:

- Simplify reused code  into functions/classes/etc.
- Organize Constant Values
- Rename variables and functions to be more accurate

## Testing and Debugging:

Ensure everything's working as well as before refactoring

## Deadline:

Milestone #2

**Comment by evnd04** [comment]
Will close but not merge yet until runtime error gets fixed
