### ISSUE TITLE
[Lecture Topic Task] Open/Closed Principle

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#254]
# For the following lecture topic task (Open/Closed Principle):
This principle states that software entities (classes, modules, functions, etc.) should be open for extension but closed for modification. This means that you should be able to add new functionality without modifying existing code.

## Objective:

Further improve upon the report map code's scalability

## Task Description:

Separate and make clear classes/functions/modules that serve as a baseline and will not be changed.

## Implementation / Subtasks:

- Create a File for Constant Values
- Create a class for Reports in report map

## Testing and Debugging:

Ensure everything's working as well as before after new additions

## Deadline:

Milestone #2

**Comment by Jjulianirizarry24** [comment]
This lecture topic task was implemented with the Refactor Report Map PR

**Comment by evnd04** [comment]
Will close but not merge yet
