### ISSUE TITLE
Add Appendix Section

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#263]
**Objective:**

Create an Appendix section in the project documentation, ensuring that it contains supplementary information such as documentation standards and other relevant material. The Appendix should not be part of the main body and must be positioned before the Log Book, which is to remain the very last section of the document.

---

**Task Description:**

The task involves compiling supplementary information that is only relevant to a smaller group of readers, such as contributors. According to the professor’s guidance, documentation standards and other technical details should not be placed at the beginning of the document, as they are not of interest to the broader audience. Instead, they should be included in the Appendix. 

The Appendix should be distinct and clearly marked, providing easy reference for contributors while keeping the main document focused on more broadly relevant content.

The Log Book, which details the project’s contributions and closed tasks, should follow the Appendix and remain the final section of the document.

---

**Implementation:**

1. **Identify Supplementary Information:** Review the document for any sections or content, such as documentation standards or other internal guidelines, that are not directly relevant to all readers.
2. **Move to Appendix:** Relocate these sections to the Appendix. The Appendix should be clearly labeled and positioned before the Log Book.
3. **Ensure Separation from Log Book:** The Log Book must remain as the very last section of the document. Ensure there is a clear separation between the end of the Appendix and the start of the Log Book.
4. **Organize the Appendix:** Structure the Appendix in a logical manner. Group similar topics together (e.g., documentation standards, coding practices, internal workflows).

---

**Subtasks:**

1. **Identify Content for the Appendix:**
   - Locate all sections that are of interest only to contributors (e.g., documentation standards, technical guidelines).
   
2. **Relocate Content to the Appendix:**
   - Move this content to the newly created Appendix section, ensuring it is well-organized and clearly marked.

3. **Ensure Log Book Positioning:**
   - Double-check that the Log Book remains the very last section of the document, after the Appendix.

4. **Organize and Review the Appendix:**
   - Ensure the Appendix is structured and includes headings for easy reference (e.g., “Documentation Standards,” “Coding Guidelines”).

---

**Testing and Debugging:**

Review the document to ensure:
- The Appendix contains all relevant supplementary information.
- The Log Book is the final section of the document, clearly separated from the Appendix.
- The overall document structure flows logically from the main content to the Appendix and finally to the Log Book.

---

**Deadline:**

Complete the Appendix section by **Monday, October 21, 2024, at 11:00 PM (23:00)**, in alignment with the week of the Milestone 2 deadline.

**Comment by evnd04** [comment]
I dont remember seeing an appendix section for the documentation criteria, is this neccesary?

**Comment by lex939** [comment]
This issue is based on the following feedback from the professor:

> Your documentation standards and some of the other stuff up front could be an appendix. They definitely do not belong here at the very start of the document, since they are only of interest to a small portion of the readers namely the contributors.

Full feedback is on Moodle and also @ #269.

**Comment by JuanJRivera** [comment]
Completed [here](https://docs.google.com/document/d/1_wP3GOpOTexKhcp-WD7vQ7LvWcJn5lpBgYzgaBjY_AE/edit#heading=h.i78af77g43mg).
