### ISSUE TITLE
[Lecture Topic Task] Document Factory Patterns

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#265]
**Objective:**

Document the team’s implementation of at least one factory design pattern. The factory should provide an abstraction layer for object creation, ensuring that complex logic behind which specific class to instantiate is encapsulated within a factory class.

---

**Task Description:**

The task involves documenting the use of the factory pattern in the project. Factories are used to simplify object creation by moving the construction logic into a dedicated factory class. This allows for flexible, maintainable code and hides complex instantiation choices. The documentation should include:
- The initial approach of exposing direct constructors for different sub-classes.
- The decision-making process leading to the use of a factory class.
- How the factory API abstracts the complexity of object creation and selects the appropriate subclass to instantiate.

---

**Implementation:**

1. **Describe the Initial Approach:**
   - Document the initial approach where constructors of different sub-classes were directly exposed.
   - Include examples of how this was initially done and why the team decided to shift to a factory pattern.
   
2. **Explain the Factory Pattern Application:**
   - Describe how the factory class was implemented to encapsulate the instantiation logic.
   - Include details on the factory’s API, showing how it provides entry points for creating objects without exposing the complex logic behind which object is instantiated.

3. **Showcase a Practical Example:**
   - Provide at least one real-world example of how the factory pattern is applied in the project.
   - This could include code snippets demonstrating how the factory simplifies object creation and hides the complexity of subclass selection.

4. **Clarify the Benefits of Using the Factory:**
   - Explain how the factory pattern improves maintainability, scalability, and flexibility in the project.
   - Emphasize how it abstracts away instantiation details and centralizes object creation logic.

---

**Subtasks:**

1. **Document the Initial Constructor Approach:**
   - Show how sub-classes were originally instantiated directly.
   - Discuss the limitations or issues that prompted the move to a factory pattern.

2. **Explain the Factory Class:**
   - Detail how the factory class was designed, including API entry points.
   - Document how complex choices (e.g., which subclass to instantiate) are handled behind the scenes.

3. **Provide an Example:**
   - Include a practical example with code snippets showing how the factory pattern is used within the project.

4. **Highlight Advantages:**
   - Explain the benefits of using a factory pattern for object creation.
   - Emphasize how this approach enhances code organization and reduces coupling.

---

**Testing and Debugging:**

After documenting the factory pattern:
- Ensure the documentation is clear and includes relevant examples.
- Verify that the description accurately reflects how the factory pattern was implemented.
- Check that the benefits of the factory pattern are clearly explained and supported by examples.

---

**Deadline:**

Complete the task by **Monday, October 21, 2024, at 11:00 PM (23:00)**, in alignment with the week of the Milestone 2 deadline.

**Comment by JorgeC08** [comment]
@lex939  Hi Lex, I already made the task. Where on the documentation it should go?

**Comment by lex939** [comment]
Place as 2.3.2

**Comment by lex939** [comment]
@YanehRuiz Ready to be closed
