### ISSUE TITLE
Document Repository Implementation and Usage

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#266]
**Objective:**

Document the implementation and use of repositories in the project. Repositories should provide an interface that exposes persistence-related functions, abstracting away the details of data storage while allowing the domain or application layer to interact with data through a clean, well-defined API.

---

**Task Description:**

The task involves documenting how the team has implemented repositories to manage data persistence. Repositories act as a bridge between the domain or application layer and the underlying data storage system. The documentation should cover:
- How repositories expose persistence-related functions.
- How they abstract data storage details, allowing the domain layer to focus on business logic.
- How repositories interact with the data layer while maintaining a clean separation from the rest of the application.

---

**Implementation:**

1. **Describe the Role of Repositories:**
   - Document the purpose of repositories in the project. Repositories should handle the details of data storage and provide a simple interface to the domain or application layer for accessing and manipulating data.

2. **Explain the Repository Interface:**
   - Describe the interface exposed by the repository, listing the persistence-related functions provided (e.g., saving, retrieving, updating, or deleting data).
   - Include details on how the repository interacts with the underlying data storage system (e.g., database, file system).

3. **Illustrate with an Example:**
   - Provide at least one example of how the repository is used in the project.
   - This could include code snippets demonstrating how the repository is called from the domain or application layer, focusing on how the repository abstracts data storage concerns.

4. **Clarify the Benefits of Repositories:**
   - Explain how using repositories improves the structure of the application by providing a clean separation between the data layer and the domain layer.
   - Discuss how repositories make the application more maintainable by encapsulating persistence logic in one place.

---

**Subtasks:**

1. **Document the Purpose of Repositories:**
   - Explain the role of repositories in handling data persistence.
   - Clarify how they provide a layer of abstraction between the domain/application layer and the data storage.

2. **Describe the Repository Interface:**
   - Detail the persistence-related functions exposed by the repository (e.g., save, retrieve, update).
   - Provide a description of how the repository interacts with the underlying data storage.

3. **Provide an Example:**
   - Include a code example demonstrating how the repository is used by the domain or application layer.

4. **Highlight Advantages:**
   - Explain the benefits of using repositories, such as improved maintainability, flexibility, and separation of concerns.

---

**Testing and Debugging:**

After documenting the repository implementation:
- Ensure the documentation is clear and provides practical examples.
- Verify that the repository's role in abstracting data storage is well-explained.
- Confirm that the benefits of using repositories are effectively communicated and supported by examples.

---

**Deadline:**

Complete the task by **Monday, October 21, 2024, at 11:00 PM (23:00)**, in alignment with the week of the Milestone 2 deadline.

**Comment by JorgeC08** [comment]
@lex939  Hi Lex, I already made the task. Where on the documentation should I put it??

**Comment by lex939** [comment]
@JorgeC08 Place as 4.3.1

**Comment by JorgeC08** [comment]
Created the section and added the information, if there's anything else let me know.

**Comment by lex939** [comment]
@YanehRuiz ready to be closed
