### ISSUE TITLE
Unveil Hidden Domain Concepts to Refine Ubiquitous Language

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#268]
**Objective:**

Document at least three examples where the team started with an initial understanding of the domain and later discovered hidden concepts. Explain how these hidden concepts were identified, made explicit, and how this affected the project’s ubiquitous language.

---

**Task Description:**

The task focuses on documenting instances where the team encountered implicit concepts within the domain that were not initially recognized. After identifying these hidden concepts through discussion and analysis, the team made them explicit, leading to an evolution in the project’s ubiquitous language. The documentation should:
- Provide three examples of implicit concepts that were identified.
- Explain how these concepts were uncovered.
- Describe the process of making these concepts explicit and how it changed the project’s language and overall understanding of the domain.

---

**Implementation:**

1. **Describe Initial Understanding of the Domain:**
   - Start by describing the initial understanding of the domain, outlining the key assumptions and concepts the team started with.
   
2. **Identify Hidden Concepts:**
   - For each of the three examples, document the moment when the team realized that an important concept was missing or hidden.
   - Explain how these hidden concepts were discovered (e.g., through discussion, domain analysis, or feedback).

3. **Make the Concepts Explicit:**
   - For each hidden concept, describe the process the team followed to formalize and make the concept explicit.
   - Document any changes made to the project’s structure, logic, or terminology as a result.

4. **Explain Changes to Ubiquitous Language:**
   - For each example, explain how the team’s discovery and formalization of the hidden concept affected the project’s ubiquitous language.
   - Highlight how the new language and concepts improved clarity and communication within the team and with stakeholders.

---

**Subtasks:**

1. **Describe Initial Domain Understanding:**
   - Document the team’s initial assumptions and understanding of the domain before the hidden concepts were discovered.

2. **Identify and Explain Hidden Concepts (Three Examples):**
   - Provide at least three examples where hidden concepts were uncovered.
   - Explain the process behind identifying each hidden concept.

3. **Describe How Each Concept Was Made Explicit:**
   - Document how the hidden concepts were made explicit.
   - Highlight any changes to project structure or logic as a result of formalizing the concepts.

4. **Document Changes to Ubiquitous Language:**
   - Explain how the identification of these hidden concepts changed the project’s language and communication.
   - Provide examples of how the new language improved understanding within the team.

---

**Testing and Debugging:**

After documenting:
- Ensure that the three examples are clearly explained and show distinct instances of discovering implicit concepts.
- Verify that the process of making the concepts explicit is detailed and understandable.
- Review the changes to the ubiquitous language to ensure the impact on the project is clearly communicated.

---

**Deadline:**

Complete the task by **Monday, October 21, 2024, at 11:00 PM (23:00)**, in alignment with the week of the Milestone 2 deadline.

**Comment by misaelmercado1** [comment]
@lex939 where would this go in the documentation?

**Comment by misaelmercado1** [comment]
Finished this task but do not know where it should go in the documentation
[Unveil Hidden Domain Concepts to define Ubiquitous Language.docx](https://github.com/user-attachments/files/17464368/Unveil.Hidden.Domain.Concepts.to.define.Ubiquitous.Language.docx)

**Comment by lex939** [comment]
> @lex939 where would this go in the documentation?

Please put this as 4.9.1. Thank you.

**Comment by misaelmercado1** [comment]
added to 4.9.1
