### ISSUE TITLE
Document the Progress of Prop Flow in React Native Application

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#272]
Objective
The objective of this task is to document the current state of the prop flow in the React Native application. This will involve capturing how props are transmitted between components and identifying potential inefficiencies such as prop drilling or redundancy. The documentation will serve as part of the final project report.

Task Description
This task involves documenting the current prop flow through the application's components. The focus is on creating a visual map of the current flow of props, identifying areas where inefficiencies might occur, and gathering feedback on the flow’s structure. No optimization steps will be taken at this stage. Instead, the documentation will provide a comprehensive analysis of the current state, helping guide future decisions. Feedback and iterations will also be recorded, and visual diagrams will be included in the final report.

Implementation
Collect Initial Data

Obtain details on how props are currently passed between components.
Create an initial diagram to map out the flow of props in the application.
Examine the diagram to identify areas where prop drilling or excessive re-renders occur.
Record findings, detailing specific inefficiencies and their potential impact on performance.
Examine the diagram to identify potential issues such as prop drilling or redundant data transmission.

Analyze the prop flow
Record findings, documenting specific inefficiencies and how they impact the current architecture.
Document any feedback received during the optimization process and how it was used to refine the approach.
Note any iterations made based on this feedback.

Subtasks
Collect information about the current state of the prop flow.
Create a visual diagram that represents how props are passed in the application.

Analyze Prop Flow:
Identify areas where prop drilling or unnecessary re-renders are present.
Document these findings for later reference.

Capture any feedback given during the process and note changes made based on it.

### Deadline
Complete the task by Tuesday, October 22, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by lex939** [comment]
Before marking this issue as Completed, please specify where in the document (aka what sections) did the changes take place. Thank you.

**Comment by JuanJRivera** [comment]
Changes are done in 2.3.1 Selected Fragments of the Implementation.

**Comment by lex939** [comment]
Loved the diagram!

However, these parts below are still missing. Please add. Thank you.

> This will involve capturing the current state of the prop flow, the analysis to identify inefficiencies, and the steps taken to optimize the flow of props.

> Identify areas where prop drilling or unnecessary re-renders are present.

> Compare performance metrics before and after the changes.

> Document any feedback received during the optimization process and how it was used to refine the approach.

**Comment by lex939** [comment]
Please keep in mind that this issue must be completed by tonight at 11:00 P.M. Thank you.

**Comment by JuanJRivera** [comment]
The task was updated because parts of the task were performed in another task that had been created in advance by another developer. The task was done in the documentation in this section “Changes are done in 2.3.1 Selected Fragments of the Implementation.”

**Comment by YanehRuiz** [comment]
@lex939
