### ISSUE TITLE
[Lecture Topic Task] Importance of Communication

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#276]
## Objective:
Document details about the team's communication.

## Task Description:
- Communication with those responsible for fabricating the eventual solution is an important part of the designer's role
- Equally important is the communication with the source of the 'requirements' specification
    - The source might not state the requirements/needs in terms of requirements

- Includes focusing on the following specific parts:
	- Communication with fabricators of the solution.
   - Communication with the source of the requirements specification.
Communication with Domain Experts :
   - Refines understanding of the domain through constant interaction (aka communication with domain experts).
   - Using a **ubiquitous language** fosters effective communication between developers and domain experts, enabling them to discuss requirements, development plans, and features in a shared understanding.
- **Modeling out loud** involves using verbal communication to explore and refine the model, leading to a deeper understanding of the domain and the design.
- Motivation for using modules to improve communication and understanding

## Implementation:
Add as many details about the team's communication to the documentation

## Deadline:
Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by diego-velez-upr** [comment]
Added to documentation in section 4.9, requesting review in order to ensure that the guidelines were properly followed.

**Comment by evnd04** [comment]
@lex939 whenever possible approve the completion of this issue

**Comment by lex939** [comment]
@diego-velez-upr Please expand on this further and make sure to provide at least one or two examples of how these important aspects of communication were implemented in the project.

**Comment by diego-velez-upr** [comment]
@lex939 I think I have an example there already, where I talk about how the teams worked closely to design and implement the UI first, and then worked on the implementation. Do you want to add another example?

**Comment by evnd04** [comment]
@lex939 Was this completed so i can close?

**Comment by evnd04** [comment]
@lex939
