### ISSUE TITLE
[Lecture Topic Task] Important Engineering Practices

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#277]
## Objective
Document the team's research about the domain, and how they re-used “standardized” components

## Task Description
- Apply knowledge from scientific research
- Reuse “standardized” components extend the designer's repertoire, but they introduce their own constraints and trade-offs

## Implementation
Document how the team has applied knowledge from scientific research to the project, as well as how the team has re-used components.

## Deadline
Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by diego-velez-upr** [comment]
Documentation was updated to include task in section 4.8, I am requesting a documentation review to ensure proper guidelines were followed.

**Comment by evnd04** [comment]
@lex939

**Comment by lex939** [comment]
@evnd04 @diego-velez-upr I can confirm that this issue has been completed properly.
