### ISSUE TITLE
[Lecture Topic Task] Process Planning

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#278]
## Objective
Document the process (in **detail**) of planning that the team utilized for the project.

## Task Description
- Preferred order of implementation
    - What should be implemented first?
    - How should the task themselves be designed so that they lend themselves to a good order of implementation?
- Integration strategy
    - How will we bring these parts together to form the final system?

## Implementation
Document in detail the process planning that the team utilized for the project

## Deadline
Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by diego-velez-upr** [comment]
Added to documentation in section 4.7, requesting review in order to ensure adequate completion of the task.

**Comment by evnd04** [comment]
@lex939

**Comment by lex939** [comment]
This issue is ready to be closed. @YanehRuiz
