### ISSUE TITLE
Report Map New Search Bar Mock up Integration

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#281]
Objective:

Integrate the newly designed search bar into the ReportMap component to allow users to search for specific locations easily.

Task Description:

Add a search bar to the ReportMap component, ensuring that it aligns with the new mockup design. The search bar should be positioned optimally within the UI and be fully functional, allowing users to search for locations and display the results on the map.

Implementation:

Add the search bar component to ReportMap.tsx.
Position the search bar as per the design mockup.
Implement functionality to query location data and display results.
Adjust map view based on search results.
Subtasks:

Create or update the search bar component.
Integrate the search bar into ReportMap.
Test the search functionality and ensure proper integration with the map.
Testing and Debugging:

Test the search functionality with various location inputs.
Ensure search results update the map view.
Debug any styling or alignment issues with the search bar placement.

Deadline:

Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by YanehRuiz** [comment]
Please add the missing tags ^^

**Comment by JoseLQV** [comment]
![image](https://github.com/user-attachments/assets/eb5d993e-b365-4f52-a0f1-93a17d032b7a)
