### ISSUE TITLE
Report Map new Light/Dark Mode Toggle Integration of Mockup

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#282]
Objective:

Implement a toggle button to switch between Light Mode and Dark Mode in the ReportMap component, improving user experience and accessibility.

Task Description:

Add a toggle button to the ReportMap component that allows users to switch between Light Mode and Dark Mode. The toggle should be easy to access and apply changes throughout the ReportMap component to adapt the theme accordingly.

Implementation:

Add a Light/Dark mode toggle button to ReportMap.tsx.
Create theme styles for both light and dark modes.
Ensure the toggle updates the component and adjusts the map's appearance based on the selected theme.
Subtasks:

Design the toggle button and determine optimal placement.
Implement theme styles and integrate with the toggle functionality.
Test the theme transition and ensure consistency across the component.
Testing and Debugging:

Test switching between Light and Dark modes for visual consistency.
Ensure that all UI elements adapt correctly to the theme.
Debug any issues with theme transitions or component styling.

Deadline: Milestone 2

Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by YanehRuiz** [comment]
Please add the missing tags ^^

**Comment by JoseLQV** [comment]
![image](https://github.com/user-attachments/assets/17dcfed2-0bc8-40fd-b9e9-f5b1e4ec751b)
![image](https://github.com/user-attachments/assets/259d36ed-11a8-49a8-bbbf-ef50577ae3f3)

**Comment by evnd04** [comment]
Is there no way the map could be in dark mode?
