### ISSUE TITLE
Report Map new Mockup Design integration for the Redesign Bottom Buttons

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#283]
Objective:

Update the design of the "Add A Report," "Current Location," and "Notification" buttons in the ReportMap component to align with the new mockup and enhance usability.

Task Description:

Redesign the bottom buttons in the ReportMap component:

Add A Report: Update the design for adding comments, making it more intuitive.
Current Location: Improve the design to make it more visible and user-friendly.
Notification: Refine the notification button to better alert users of new reports.
Implementation:

Update the design and styles for each button.
Ensure the new designs are responsive and align with the overall app theme.
Maintain existing functionality while adapting to the new design.
Subtasks:

Update "Add A Report" Button:

Redesign to make it clearer that the feature is for adding comments.
Test the new design for usability.
Redesign "Current Location" Button:

Update the button style for better visibility.
Ensure functionality remains intact.
Refine "Notification" Button:

Update the design for easier recognition.
Test notifications to ensure they function as intended.
Testing and Debugging:

Test each button’s functionality after design updates.
Ensure the designs look consistent in both Light and Dark modes.
Debug alignment or visibility issues during testing.

Deadline: Milestone 2

Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by YanehRuiz** [comment]
Please add the missing tags ^^

**Comment by JoseLQV** [comment]
![image](https://github.com/user-attachments/assets/9c2f9031-404e-4ea5-ae69-7f79dae17aa8)



![image](https://github.com/user-attachments/assets/874584e2-cfbc-4f6f-9fae-db18a95ffeee)
