### ISSUE TITLE
[Lecture Topic Task] Relationship to Extreme Programming

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#284]
Objective:

Implement Extreme Programming into the trust system team's code.

Task Description:

Review and Document the Trust Systems code for implementation of Extreme Programming.

Implementation:

Implement Extreme Programming principles into the codebase, reviewing and altering existing code, and implementing it into future code.

Deadline:

Complete the task by Monday, October 21, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

Link for the evidence of the [LLT](https://docs.google.com/document/d/1u_reZqh-gUkvUOMoGk_z7zKb_KnOZEUcRLPc42FAlpg/edit?usp=sharing)

**Comment by lex939** [comment]
Ubiquitous language is already defined on another issue (#276). Therefore, this issue does not seem viable. Please try either creating another Lecture Topic Task or expanding on this one with more lecture topics to make this issue fortified enough to justify it.

**Comment by evnd04** [comment]
@lex939 Didnt understand your comment? Could you explain in depth why this issue wouldnt be viable?

**Comment by evnd04** [comment]
@lex939 i feel this is more implementation-focused than issue #276 or am i wrong @Alejandro-DeJesus?

**Comment by Alejandro-DeJesus** [comment]
> @lex939 i feel this is more implementation-focused than issue #276 or am i wrong @Alejandro-DeJesus?

Yeah, it's more of implementing the practice, with the documentation aspect serving more of proof of implementation.

**Comment by Alejandro-DeJesus** [comment]
Evidence of Code Changes: https://docs.google.com/document/d/1u_reZqh-gUkvUOMoGk_z7zKb_KnOZEUcRLPc42FAlpg/edit?usp=sharing
