### ISSUE TITLE
Workflow diagram for EditProfile and UserAuthentication

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#29]
Objective:
The objective of this task is to create workflow diagrams for two key components of the application: the EditProfile and UserAuthScreen components. These diagrams will help visualize the flow of interactions, state changes, and data transitions within these components, aiding in documentation and future development.

Task Description:
This task involves the creation of two workflow diagrams that accurately depict the behavior of the EditProfile and UserAuthScreen components.

EditProfile Workflow Diagram:
- Visualize the process of editing a user's profile, including the steps for viewing, modifying, saving, or canceling changes, and passing updated data back to the parent Profile component.
UserAuthScreen Workflow Diagram:
- Show the flow of user interactions in the authentication screen, including the toggling between the sign-up and login forms, user authentication, and the transition to the - ReportScreen upon successful login or sign-up.

These diagrams will be used for documentation and onboarding purposes, as well as to assist in understanding the functionality of these critical components.

Implementation:
EditProfile Diagram:
* Review the EditProfile and Profile components to identify state variables, prop functions, and key interactions.
* Translate the flow of state changes (edit mode, save/cancel actions) into a clear diagram.
UserAuthScreen Diagram:
* Analyze the UserAuthScreen, UserLogin, and UserSignup components, focusing on the toggle mechanism between login and sign-up, user authentication, and rendering logic.
* Build a workflow diagram showing the transitions between the forms and successful/failed authentication flows.
Tools:

Use diagramming tools to create clear, interactive diagrams.

Subtasks:
EditProfile Workflow Diagram:

* Identify the key interactions and state updates in the EditProfile and Profile components.
* Create the diagram representing the process of entering edit mode, updating profile information, and returning to the profile screen.
UserAuthScreen Workflow Diagram:

* Map out the interaction between UserAuthScreen, UserSignup, UserLogin, and ReportScreen.
* Visualize the transitions between sign-up and login forms, and the steps after user authentication.

Testing and Debugging:
The diagrams will be reviewed for accuracy by cross-referencing the components and verifying the state and flow logic.
Feedback from developers and stakeholders will be collected to ensure that the diagrams are comprehensive and reflect real implementation.
Iterative changes will be made based on feedback.

Deadline: October 25, 2024

**Comment by noel-vargas** [comment]
![image](https://github.com/user-attachments/assets/888fcb02-a2f0-4e6e-bc7b-d8a71c651635)
