### ISSUE TITLE
 [Lecture Topic Task] Application Navigation Scheme 

### ISSUE THREAD

**Issue by Rodal1** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#292]
Objective:

Document the navigational structure of the application in a tree scheme format. This will help developers understand how users will interact with the app’s features.

Task Description:

The tree scheme will represent how users move from the Home Page through different tabs and sections of the app. Each tab or section will be described in terms of its purpose, how it connects to other parts of the app, and the user’s expected interactions. The documentation will include:

    A visual tree diagram or map.
    A detailed breakdown of each page and its sub-pages.
    Descriptions of the functionality provided by each section.

Implementation:

A tree scheme can be followed, where the root controls the routing for different pages such as the Home Page, Profile, Settings, and Reports. From the Home Page, users will have access to core features like viewing and managing reports in the Reports Section, updating account details in the Profile Section, or configuring settings in the Settings Page. Authentication will be managed through the Login Page and the User Authentication Screen to ensure secure access. Each section, such as reports or profile, will be composed of subpages, such as viewing a report or editing the user profile. The application should implement routing based on the navigation tree to ensure smooth transitions between sections while maintaining user session and data state.

Deadline:

Milestone 2 (October 25, 2024)

**Comment by Rodal1** [comment]
Added on page 51 of Documentation.

**Comment by Rodal1** [comment]
@lex939

**Comment by evnd04** [comment]
@lex939
