### ISSUE TITLE
Milestone 2 Presentation Slide Deck Contribution

### ISSUE THREAD

**Issue by Jjulianirizarry24** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#294]
Add Location Management Team progress in the Milestone #2 Slide Deck.

**Comment by evnd04** [comment]
Whenever the task is being done try to add a demo of features created for this milestone, preferably speak and explain some of the feature. And remember to try and not overload slides with text, last presentation was more introductory so no need for an intro to the team for this milestone.
