### ISSUE TITLE
Design the UI for viewing the report rules and guidelines

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#295]
## Objective

Design the UI for viewing the rules and guidelines that the users must follow with regard to reports.
The rules and guidelines are documented in issue #217.

## Task Description

Design in the [Trust System Team's Figma](https://www.figma.com/design/RkeUIrPmXuTs9OCbmTsNq7/Trust-System-Team?node-id=0-1&t=sD04n3pHomJ9mufe-1) the UI for users to view the rules and guidelines they must follow.

## Implementation

No implementation design has been agreed upon yet, but this could be a simple scrollable text view that the users could access from a *rules* section within settings.

## Deadline

Milestone 3

**Comment by jonVargas1** [comment]
<img width="187" alt="Screen Shot 2024-11-19 at 1 17 47 PM" src="https://github.com/user-attachments/assets/0985ae5a-4edc-4076-b0e8-77a4027fed8a">
