### ISSUE TITLE
Design the UI for notifying first time reporters of the rules and guidelines

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#297]
## Objective

Design the UI for notifying first time reporters of the rules and guidelines that they must follow when submitting reports.
The rules and guidelines should be documented in issue #217.
Depending on implementation, this task could depend on #296.

## Task Description

Design in the [Trust System Team's Figma](https://www.figma.com/design/RkeUIrPmXuTs9OCbmTsNq7/Trust-System-Team?node-id=0-1&t=sD04n3pHomJ9mufe-1) the UI for notifying first time reporters of the rules and guidelines they must follow when submitting a report.

## Implementation

No implementation design has been agreed upon yet, but I think that this could be a pop-up with the rules and guidelines when a user goes to create a report. The reason that this could depend on #296 is because we could either use the same component used for that task, or we could make a new one for it. 

We should probably favor re-using the component from #296 to avoid code duplication and introducing technical debt.

## Deadline

Milestone 3

**Comment by jonVargas1** [comment]
Design for pop-up for first time users when they attempt to create a report for the first time:
<img width="333" alt="Screen Shot 2024-11-10 at 1 24 56 PM" src="https://github.com/user-attachments/assets/be9d6fca-80b1-428d-aab8-6581de6d5482">

Design for users who wish to see a more detailed explanation of the guidelines, or who wish to see them after the first time:
<img width="288" alt="Screen Shot 2024-11-10 at 1 18 04 PM" src="https://github.com/user-attachments/assets/711106ea-8ae8-446f-bdf7-9737f70e5d03">
