### ISSUE TITLE
Report Object Life Cycle Notification System

### ISSUE THREAD

**Issue by javier-rivera8** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#300]
Objective:

- Create a notification system that alerts the user when reports are about to be automatically deleted. The system will notify users a few days before the deletion deadline, allowing them to take action if needed, ensuring that important reports are not removed without the user’s awareness.

Task Description:

- The task is to design and implement a notification system that integrates into the current report management feature. The notification will trigger a reminder to users a set number of days before reports are due for automatic deletion.

Implementation:

- Notification Triggers: Set up automated triggers based on report creation/deletion timestamps. These triggers will activate notifications at specified intervals (e.g., 3 days before report deletion).

- Notification Channels: Implement different types of notifications (e.g., email, push notifications). This would require creating templates for each channel and ensuring they are sent at the correct time.

Testing and Debugging:

- Manual Testing: Use real scenarios to manually test how and when notifications are sent. Ensure that notifications appear in the app and through other channels (email/push) correctly.
- Error Handling: Implement checks for failed notification deliveries and log any issues for debugging.
- Integration Tests: Verify that the notification system interacts seamlessly with the report history and deletion system.

Deadline:

- Milestone 2

**Comment by lex939** [comment]
This is not a lecture topic task. Please specify which Lecture Topic(s) specifically will be used for this issue.

Specifying the life cycle of something is too broad of a concept and cannot be designated as an LT. An LT needs to be more focused than that.

**Comment by javier-rivera8** [comment]
The task is related with the object life cycle of the reports, having lots of reports without deletion may put the system slow and bring complex problems. This is why I am creating this task, to implement the notification to notify the user of when the reports are going to be deleted.

### The life cycle of a domain object:
Creation
Modification
_**Storage**_
Reconstitution
Archiving
_**Deletion**_
