### ISSUE TITLE
[Lecture Topic Task] Single Responsibility Principle: Authentication + User modules

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#303]
### Objective
Instead of a separate module for user authentication database operations, all user-related operations will be stored in a single class. 

### Task Description
The `users` blueprint will be responsible for all user-related CRUD operations. Any authentication process (`.../db/blueprints/auth.py`) will be carried out externally and counting on the `users` module being open for scalable functionality. 

### Implementation
To consider this task completed, all user-related responsibilities will be carried out by the `users` blueprint. 

### Subtasks
1. Move user registration functionality from `auth` blueprint to `user` blueprint. 
2. Check for previous user registration function calls and restructure accordingly.
3. Remove unused `auth` blueprint.
4. Ensure proper app functionality.

### Testing and Debugging
Run app and check for equivalent performance as compared before and after architecture change. 

### Deadline
This task will be completed by the end of Milestone 2 on October 25th 2024.

**Comment by lex939** [comment]
This is fine with me, but make sure to also document your application of the Lecture Topic Task within the documentation.
