### ISSUE TITLE
[Lecture Topic Task] Add Layered Architecture Diagram to the Documentation

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#304]
Objective:
Provide a visual representation and clear explanation of the project’s layered architecture to improve the documentation. This will help developers, stakeholders, and collaborators understand the structure, responsibilities, and dependencies within the system.

Task Description:
This task involves integrating the Layered Architecture Diagram into the project’s documentation. The goal is to ensure that each layer is clearly defined and that the relevant files and components are aligned within their appropriate layers. This will provide better insights into how different parts of the system interact, enhancing maintainability and facilitating onboarding for new developers.

Implementation:
Create a diagram that contains the layers and the respective files.
Document Each Layer: Include each layer and the files it contains:

Subtasks:

Update the documentation file with the following:
Diagram with his respective title
Description of the layers

Testing and Debugging:

Visual Check: Verify that the diagram is correctly displayed in the documentation.
Content Review: Ensure that each file is placed in the appropriate layer and the descriptions are accurate.

Deadline:

Complete the task by Thursday, October 24, 2024, at 11:00 PM (23:00), in alignment with the week of the Milestone 2 deadline.

**Comment by JuanJRivera** [comment]
Implementation is on section "2.1 Implementation".

**Comment by YanehRuiz** [comment]
@lex939
