### ISSUE TITLE
[Lecture Topic Task] Session Timeout and User Inactivity Handling

### ISSUE THREAD

**Issue by johnsantiago9** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#307]
Objective: Implement a session timeout feature to enhance the security of the SafeRUM authentication system by automatically logging out inactive users after a specified period. This task will help protect users from unauthorized access to their accounts in case they leave their devices unattended.

Task Description: This task focuses on implementing session timeout functionality within the SafeRUM app. The goal is to ensure that user sessions automatically expire after a period of inactivity, thereby preventing unauthorized access in cases where users forget to log out or leave their devices unattended. Additionally, the task will involve handling session renewal for active users to provide a balance between user convenience and security. The system should be flexible to allow the timeout duration to be adjusted and configurable based on security needs.

Implementation:

Set Session Timeout Duration: Determine an appropriate inactivity period for session expiration, for example, 15-30 minutes of inactivity.
Monitor User Activity: Track user actions such as clicks, typing, or page navigation to determine if the session should be kept active.
Implement Session Timeout Logic: Set up the backend and frontend to handle session timeout. This includes:
Logging the user out after the inactivity period expires.
Displaying a warning message before automatic logout.
Session Renewal: If the user is active, extend the session duration without requiring a re-login. This will maintain usability while still securing inactive sessions.
User Notification: Implement a pop-up that notifies the user that their session is about to expire, allowing them to take action to stay logged in.
Session Expiry Flow: Upon session expiry, redirect the user to the login page with a notification explaining that their session has timed out due to inactivity.
Subtasks:

Define Inactivity Timer:
Configure a timer that resets every time the user interacts with the app (mouse movement, keyboard input, page changes).
Set a customizable timeout duration (e.g., 15 minutes of inactivity).
User Notification on Timeout:
Create a warning notification that appears 1-2 minutes before the session expires, prompting the user to click or perform an action to stay logged in.
Auto-Logout Functionality:
Implement backend logic to terminate the session after the inactivity period has passed.
Ensure that all session tokens or cookies are invalidated upon timeout.
Testing on Multiple Devices:
Test the session timeout functionality on various devices (smartphones, tablets) and platforms (iOS, Android) to ensure it behaves as expected across different environments.

Deadline Milestone 2

Urgency 5
Difficulty 5

**Comment by johnsantiago9** [comment]
The task described refers to the "Security Features" or  "Session Management" lecture topics. Specifically, it involves applying techniques discussed in class to improve authentication security by handling user session timeout and renewal, ensuring protection against unauthorized access due to inactivity.

**Comment by evnd04** [comment]
How does this relate to a lecture topic?

**Comment by YanehRuiz** [comment]
Question answered on the comment prior, closing this issue as completed.
