### ISSUE TITLE
Design registration form UI

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#31]
### Objective
Obtain a schematic to help visualize and communicate the structure of the user account creation page. 

### Task Description
User account creation must be a smooth user experience while collecting necessary information securely. The focus of this task is to design an intuitive, user-friendly, and visually appealing registration form UI. 

### Implementation
This task is centered around UI/UX design, therefore requiring the creation of wireframes and/or mockups of the user registration form. Rough sketching is encouraged in whatever methodology best suits the developer, but a digital representation of the design is preferred to close the task. That could involve the usage of an online tool like Miro or Figma, for example. 

### Subtasks
1. **UI/UX Research**: The developer might find it useful to identify best practices for UI/UX design. 
2. **Requirement gathering**: Gather requirements regarding the fields and validations for the form, i.e. password confirmation, the required `upr.edu` email domain, etc. 

### Testing and Debugging
Final review and approval will come from the team leader and managers. However, feedback from other stakeholders and users is greatly encouraged to make the necessary adjustments. Remember: The focus is to ensure intuitiveness and user-friendliness. 

### Milestone
The wireframe should be designed and reviewed by September 10th, 2024. 
https://www.figma.com/design/RIkJfzdeSH5rTBQ2MyYYX5/CreateAccount?node-id=0-1&t=xhTB2RMnRtK6y2RW-1

**Comment by evnd04** [comment]
Same with the other task, send this link to the joint figma issue.
