### ISSUE TITLE
Allow database to receive & store Firebase JWT from user signup

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#323]
**Objective:**

Enable the backend to securely receive, validate, and store Firebase JWTs from new users upon signup. Storing JWTs will facilitate session management, user validation, and seamless access to resources.

---

**Task Description:**

The task involves setting up the backend to accept Firebase JWTs from users upon signup, validating these tokens, and then storing user information in the database for future reference and validation. The process will include decoding the JWT to extract user details (like UID, email), securely saving relevant details in the database, and storing the token for session management or analytics purposes.

---

**Implementation:**

1. **Receive Firebase JWT on Signup**:
   - Create an API endpoint to handle incoming signup requests containing the Firebase JWT.
   - Extract the token from the request and pass it to the Firebase Admin SDK for validation.

2. **JWT Validation**:
   - Use Firebase Admin SDK to decode and validate the JWT.
   - Retrieve user details like UID, email, and display name from the decoded token payload.

3. **Store User Details in the Database**:
   - Create a user model or table to store essential user details and the JWT, if required.
   - Store fields like Firebase UID, email, display name, signup timestamp, and JWT (optional for analytics, not recommended for long-term storage).

---

**Subtasks:**

1. **Set Up Firebase Admin SDK for JWT Decoding**:
   - Initialize Firebase Admin SDK with the service account to enable JWT decoding and validation.

2. **Implement Signup Endpoint**:
   - Define a POST endpoint (e.g., `/api/signup`) to receive Firebase JWTs and handle new user signup.
   - Use Firebase Admin SDK to decode the token and retrieve user details.

3. **Database Integration**:
   - Create a user table/model with columns like `firebase_uid`, `email`, `display_name`, and optional `jwt` for session tracking or analytics.
   - Save decoded user information into the database upon successful signup.

4. **Environment Configuration**:
   - Securely store Firebase credentials using environment variables.
   - Document environment configuration steps in `.env.example` for secure deployment.

---

**Testing and Debugging:**

- **Unit Testing**: Test the JWT validation logic with valid and invalid tokens to ensure it correctly verifies authenticity.
- **Database Checks**: Manually confirm the stored user details in the database after signup requests to ensure accuracy.

---

**Deadline:**
October 25th, 2024

**Comment by evnd04** [comment]
Will not merge till error is fixed, will close the issue tho
