### ISSUE TITLE
Implement Firebase API boilertplate code in backend

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#324]
**Objective:**

Integrate Firebase Authentication to enable secure user login and session management on the backend. This will provide authentication middleware for verifying user tokens and controlling access to protected routes.

---

**Task Description:**

The task involves setting up Firebase Authentication in the backend to handle user login sessions. This setup will include initializing Firebase Auth, creating middleware to verify ID tokens from Firebase, and defining a login route if needed to verify credentials or initiate user sessions. 

---

**Implementation:**

1. **Set Up Firebase Admin SDK for Authentication**:
   - Obtain Firebase service account credentials and initialize the Firebase Admin SDK.
   - Configure environment variables to securely store Firebase API keys and service credentials.

2. **Token Verification Middleware**:
   - Create middleware to verify Firebase ID tokens in incoming requests.
   - Decode the ID token to retrieve user information and enforce access control where necessary.

3. **Login Endpoint** (if custom token or additional processing is needed):
   - Optionally set up an endpoint to handle client login requests if additional processing (e.g., role checks) is required.
   - Use the Firebase Admin SDK to verify the token and respond with user info or session details.

---

**Subtasks:**

1. **Setup Firebase Admin SDK with Service Account**:
   - Initialize Firebase in the backend using credentials from the team app.

2. **Implement Authentication Middleware**:
   - Write middleware to validate incoming Firebase ID tokens.
   - Extract user info from tokens for additional session logic if needed.

3. **Environment Setup**:
   - Store Firebase keys and service credentials in environment variables for secure configuration.
   - Document configuration steps and required environment variables in a `.env` file.

---

**Testing and Debugging:**

- **Unit Testing**: Test the token verification middleware to ensure it correctly validates and rejects invalid tokens.
- **Manual Testing**: Test with Firebase’s generated tokens from the frontend to confirm successful login and access control.

---

**Deadline:**
October 25th, 2024

**Comment by evnd04** [comment]
Will close this issue but not merge right now until the runtime error is fixed
