### ISSUE TITLE
Fix error at runtime

### ISSUE THREAD

**Issue by evnd04** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#331]
Task Description:

The task involves identifying and resolving the uncaught error that arises when attempting to access the navigation object. The error message indicates that the component using useNavigation is not inside a NavigationContainer. The goal is to ensure that all components requiring navigation access are properly wrapped within the NavigationContainer, allowing them to use the useNavigation hook without issues.

Implementation:

Review and Refactor Components:

Inspect the components throwing the error (in this case, ReportDeletion.tsx and possibly others) and ensure that they are rendered within the NavigationContainer. This can involve adjusting the app structure or wrapping the relevant components in the NavigationContainer.
Update Navigation Context:

Ensure that the NavigationContainer is properly set up at the root level of the app, and its context is accessible to all child components that require navigation.
Fixing the Hook Usage:

Modify the use of useNavigation to correctly handle undefined cases, ensuring the app provides meaningful error messages or fallback behavior if the navigation context is missing.
Subtasks:

Identify the Affected Components:

Use the stack trace and logs to track all components experiencing the navigation error.
Refactor the App Structure:

Adjust the app’s component tree to ensure that NavigationContainer wraps the necessary screens and components.
Ensure Proper Context Use:

Verify that all components requiring navigation are using the correct context and hooks (useNavigation) within valid NavigationContainer bounds.
Error Handling:

Add fallback logic or error messages to gracefully handle cases where the navigation object might not be available.
Testing and Debugging:

Unit Testing:

Write unit tests to confirm that components can access the navigation object and that useNavigation behaves as expected.
Manual Testing:

Manually navigate through the app’s affected screens (especially the report deletion and viewing screens) to ensure they function correctly without throwing navigation errors.
Error Handling Verification:

Simulate scenarios where the NavigationContainer might be missing to verify that appropriate error messages or fallbacks are displayed.

Deadline:
Octber 31,2024

<img width="1168" alt="Screenshot 2024-10-25 at 1 45 52 PM" src="https://github.com/user-attachments/assets/08dcd492-731d-468a-8335-2e467bef0379">

**Comment by evnd04** [comment]
@Jjulianirizarry24 @shenied-maldonado @Alejandro-DeJesus @yadrielsamir this task is due to a error at runtime that JJ brought up, the code isnt working at least on my device.

**Comment by diego-velez-upr** [comment]
I'm getting a different error from the screenshot attached.

<img src="https://github.com/user-attachments/assets/50461ea4-3b94-44f0-b7f0-275db504f879" width=400/>

**Comment by diego-velez-upr** [comment]
@yadrielsamir your PR #327 must've created this issue.

**Comment by joel-alvarado** [comment]
Replicated on my end. Agree with @diego-velez-upr . The commit that adds this package `import AddReportModal from './AddReportModal';` has the file missing.
