### ISSUE TITLE
[Lecture Topic Task] Understanding the Five Levels of Ignorance

### ISSUE THREAD

**Issue by JorgeC08** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#339]
Objective:
Introduce and document the Five Levels of Ignorance and their impact on software development.

Description:
 This task is for researching and explaining each of the Five Levels of Ignorance, focusing on how these levels can help identify knowledge gaps in the project. This documentation will provide insights into the importance of recognizing and addressing different levels of ignorance during development.

Implementation:
Provide a concise overview of each level with examples relevant to SafeRUM. Structure the document to include each level’s definition, project relevance, and personal reflections on how this awareness can improve software development.

Subtask:
- Document each level
- Project relevance reflection
- Personal insight 

Testing and Debugging:
Review documentation for clarity and ensure each level’s explanation includes relevant examples.

Deadline:
Milestone 3

**Comment by lex939** [comment]
@YanehRuiz This issue is completed and ready to be closed.
