### ISSUE TITLE
[Lecture Topic Task] Analyzing 3rd Order of Ignorance in Project Development

### ISSUE THREAD

**Issue by JorgeC08** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#341]
Objective:
Focus on 3rd Order Ignorance (lack of a process to discover unknown unknowns) and analyze its impact on the project development, using SafeRUM as a case study.

Description:
This task involves analyzing 3rd Order Ignorance and identifying areas in SafeRUM where unknowns might be missed due to a lack of process. Sugesting methods to address these unknowns, such as feedback loops or exploratory testing, that can help reveal hidden requirements or issues.

Implementation:
Document the concept of 3rd Order Ignorance and identify potential gaps in the SafeRUM project where a lack of process may lead to unknowns. Propose processes that could reduce 3OI and enhance project clarity.

Subtasks:
- Define 3rd Order Ignorance: Write a brief description of 3rd Order Ignorance and explain why it presents a challenge in software development.
- Identify Project Gaps: Identify areas in SafeRUM where a lack of process might result in missed knowledge.
- Suggest Processes: Propose two or three processes, such as periodic user feedback sessions or exploratory testing, to help convert 3OI to lower levels and address unknowns in SafeRUM.

Deadline:
Milestone 3

**Comment by JorgeC08** [comment]
@lex939  

Hi Lex, I already completed this task and created subsection 2.1.7 titled Addressing 3rd Order Ignorance.

If there's anything else let me know.

**Comment by lex939** [comment]
@evnd04 ready to close :)
