### ISSUE TITLE
[Lecture Topic Task] Document core models with boundaries and contexts for SafeRum's notification system.

### ISSUE THREAD

**Issue by misaelmercado1** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#349]
Objective:

Given that teams might make changes independently we need to define what each models purpose is within saferum so teams have clear understanding of the terminology.

Task Description:

Documentation of each of the models in the saferum app will be recorded and documented in details so teams can make use of it

Testing and Debugging:

Talk with documentation leader to see if it meets documentation criteria

Deadline:
Milestone 3 end september 26

**Comment by misaelmercado1** [comment]
https://docs.google.com/document/d/1J6IHZQXwvvMFA5II3Av0tyVl3lxf1zUwl86iXIrW00M/edit?usp=sharing

**Comment by YanehRuiz** [comment]
Remember to add this to the project document as well! 

@lex939, tagging for doc purposes
