### ISSUE TITLE
[Lecture Topic Task] Interface Segregation Principle

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#351]
### Objective
Document and elaborate on decision to create separate user interfaces with distinct purposes within SafeRUM.

### Task Description
This principle states that clients should not be forced to depend on interfaces they don't use. Instead, interfaces should be small and specific to the needs of the client. 

### Implementation
Explain design principle incorporation in SafeRUM documentation. 

### Subtasks
N/A

### Testing and Debugging
N/A

### Deadline
Milestone 3

**Comment by YanehRuiz** [comment]
@lex939
