### ISSUE TITLE
[Lecture Topic Task] Designing Intention-Revealing Interfaces

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#352]
Objective:
To simplify and enhance the SafeRum admin interface by making key actions clearer and reducing the chance of accidental triggers. This task aims to improve usability for high-stakes actions, focusing on clarity and basic error-checking.

Task Description:

Update Critical Button Labels: Focus on high-priority actions like “Send Alert,” “Deactivate User,” and “View Report.” Change any vague labels to more specific terms. For example, “Submit” becomes “Send Alert to Security.”
Add Confirmations to Emergency Actions: For actions that could have immediate impact, such as “Send Alert” or “Deactivate User,” add a simple confirmation dialog asking, “Are you sure?” This reduces accidental activation.
Use Consistent Language in Confirmations: Make sure each confirmation uses similar language for consistency (e.g., “Are you sure you want to deactivate this user? This action is immediate.”).

Subtasks :

Improve Labels and Add Tooltips
Implement Simple Confirmation Dialogs
Add Basic Assertions and Alerts for Missing Data
Perform Usability Testing and Basic Scenario Checks

Testing and Debugging:
 Test these updates with a sample admin user to confirm they’re intuitive and effective.
Scenario Test Confirmations and Assertions: Run a few quick scenarios to check that confirmation dialogs and error messages appear correctly.

Deadline:
Milestone 3

**Comment by YanehRuiz** [comment]
> @YanehRuiz @evnd04 Hi, I noticed that some of my task don't have any points assigned to them. Could you guys please verify this? Thank you

It's been fixed!
