### ISSUE TITLE
[Lecture Topic Task] Case Studies in Supple Design - Admin Interface 

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#354]
Objective:

To research and analyze real-world examples of supple design in software, focusing on successful applications and the lessons that can be applied to improve the SafeRum admin interface. This task aims to understand how supple design principles can create flexible, intuitive, and maintainable interfaces and apply these insights to SafeRum.

Task Description:

Research and analyze real-world examples of software that successfully implement supple design principles. The goal is to understand how these principles have contributed to creating flexible, intuitive, and maintainable interfaces, with a focus on identifying insights that can be applied to improve the SafeRum admin interface.

Implementation:

Review relevant case studies on supple design, focusing on real-world applications with intuitive, modular interfaces. Extract key design principles, then create a report with these insights, specifically noting which principles can improve SafeRum’s admin interface. Present a summary of findings to the team, highlighting actionable steps to make SafeRum’s interface more flexible and user-friendly.

Subtasks:

Research Case Studies in Supple Design
Summarize Key Design Principles and Lessons Learned
Create a Summary Report of this.

Testing and Debugging:

Reading Multiple Case studies and comparing them with each other and our design so far.

Deadline:

Milestone 3

**Comment by RaquelQuinones** [comment]
Here is the case study:
[Enhancing the SafeRum Admin Interface with Supple Design Principles.pdf](https://github.com/user-attachments/files/17907106/Enhancing.the.SafeRum.Admin.Interface.with.Supple.Design.Principles.pdf)

**Comment by evnd04** [comment]
Will this be added to documentation? Or is it meant to be a seperate thing?

**Comment by RaquelQuinones** [comment]
> Will this be added to documentation? Or is it meant to be a seperate thing?

This task mostly involved researching Supple Design and identifying areas for improvement within the Admin Interface Design. It is separate from the documentation, but if you would like it to be included, please let me know.

**Comment by lex939** [comment]
@RaquelQuinones This would be a good addition to Milestone 3's Documentation. When you add a section about this in the doc, please tag me and specify where in the doc you placed your info. Thank you.

**Comment by RaquelQuinones** [comment]
> [@RaquelQuinones](https://github.com/RaquelQuinones) This would be a good addition to Milestone 3's Documentation. When you add a section about this in the doc, please tag me and specify where in the doc you placed your info. Thank you.

@lex939 I have not worked on documentation so I do not know where to add this. Could you please tell me where I should add this? : )
