### ISSUE TITLE
Update Application Navigation Structure Visual

### ISSUE THREAD

**Issue by JorgeRivera94** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#366]
**Objective:**
Update the Application Navigation Structure visual on documentation to reflect report category changes.

**Task Description:**
The graph under Application Navigation Structure on Section 2.3 Implementation needs to be updated to reflect recent changes on report creation labels defined in #287.

**Implementation:**
If original document available:
* Access the document.
* Rename category labels under Reports Viewing -> Reports Creating -> Categories.
* Retake screenshot.
* Update the current image under Application Navigation Structure on Section 2.3.

If original document is not available:
* Recreate the flow chart with updated labels.
* Retake screenshot.
* Update the current image under Application Navigation Structure on Section 2.3.

**Subtasks:**
None.

**Testing and Debugging:**
Ensure flow chart accurately reflects flow in the implemented application.

**Deadline:**
November 22, 2024.

**Comment by JorgeRivera94** [comment]
@lex939 If the original document still exists, its creator could be assigned the task for time simplicity.

**Comment by JuanJRivera** [comment]
Completed en 2.3 implementation.
