### ISSUE TITLE
Correct Misquote on Section 2.1.1 Domain Rough Sketch

### ISSUE THREAD

**Issue by JorgeRivera94** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#367]
Objective:

Rewrite misquote on Section 2.1.1 Domain Rough Sketch as pointed out by the professor's feedback on M1 documentation.

Task Description:

As answered in Q&A post #247, quoting of [National Center for Education Statistics](https://nces.ed.gov/fastfacts/display.asp?id=804) should be rewritten to "Approximately 16.9 on-campus crimes reported per 10,000 FTE students enrolled" to address the professor's feedback. 

Implementation:

* Identify the sentence.
* Add context that 81 reports were filed in UPRM from January 2023 to August 2024.
* Add context about the severity of these situations.

These are the [tabulated reports](https://drive.google.com/file/d/1R_ro1CVCPU636PfHHs2jTPSIcp_TcvL2/view?usp=sharing) and the [jupyter notebook](https://drive.google.com/file/d/1ZKl_q_ZFANhltr65XxuWVa0ViDYp3BYA/view?usp=sharing) used to visualize them.

Subtasks:

If needed, edit the notebook to find any stat you deem relevant to elevate the domain rough sketch section.

Testing and Debugging:

Double check the source to make sure it's quoted correctly.

Deadline:

November 15, 2024

**Comment by JorgeRivera94** [comment]
@lex939 Was there anything else needed for this piece of feedback?

**Comment by Chosen-Juan1** [comment]
in terms of severity, they ranged from theft of campus property, to harassment (both sexual and non sexual), to altercation of peace. So, unsure what to include specifically.

**Comment by Chosen-Juan1** [comment]
full update: 
Given that the National Center for Education Statistics [reported](https://nces.ed.gov/fastfacts/display.asp?id=804) approximately 16.9 on-campus crimes reported per 10,000 FTE students that enrolled in 2021, and that it is very important that said issues with the current emergency communication system get addressed. To include some examples that are closer to home, in the UPRM, 81 reports were filed from January [2023](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2/) (47 in 2023) to August [2024](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2-2/) (34 in 2024 so far). These reports ranged from: theft of campus property ([a TV Sharp TV 70” was reported stolen in January 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-enero-2024.pdf)), to violence on campus grounds ([a student was thrown against a chair by another student in February 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-febrero-2024-eom.pdf)), to verbal harassment and threats ([a student reported that she was being threaten by an employee in april, 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/06/Informe-de-Actos-Delictivos-ABRIL-2024-.pdf)).

**Comment by Chosen-Juan1** [comment]
I think that should be all for this task

**Comment by JorgeRivera94** [comment]
Hi! I also believe this is enough to close task. 
When defining it, the "Add context about the severity of these situations." just meant to comment on how frequent high severity tasks occurred so there's no problem with what you did. If you wanted to make further changes, this topic relates to post #287 so you could read it over if you wanted.

**Comment by Chosen-Juan1** [comment]
Due to this section belonging to the domain rough sketch, if we include too much detail it would remove the "abstraction" from it. I recall reading something like that in Shutz's feedback from milestone 1, were he stated that the rough sketch should remain as abstract as possible, so I believe we should leave it like it is now. I read over issue #287 and it seems like it would be more proper to include it in another more informative section.

**Comment by JorgeRivera94** [comment]
Perfect, sounds good.

**Comment by Chosen-Juan1** [comment]
forgot that switching the label closes it, my bad

**Comment by YanehRuiz** [comment]
@lex939

**Comment by lex939** [comment]
Please indicate what you added, where added info was placed in the Google Doc, and what text was modified and/or eliminated.

Please make sure to not close issues yourself. Only Evand and Yanishka can do this. 

Thank you.

**Comment by Chosen-Juan1** [comment]
What was added is mentioned here, the section modified is section 2.1.1, and here is a pic of the modified text highlighted. in grenn @lex939 
<img width="1440" alt="Screenshot 2024-11-11 at 9 12 48 PM" src="https://github.com/user-attachments/assets/9168adf2-bbdc-4b5e-ac81-72d71c1f3de1">


> full update: Given that the National Center for Education Statistics [reported](https://nces.ed.gov/fastfacts/display.asp?id=804) approximately 16.9 on-campus crimes reported per 10,000 FTE students that enrolled in 2021, and that it is very important that said issues with the current emergency communication system get addressed. To include some examples that are closer to home, in the UPRM, 81 reports were filed from January [2023](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2/) (47 in 2023) to August [2024](https://www.uprm.edu/calidaddevida/informe-de-actos-delictivos-2022-2-2/) (34 in 2024 so far). These reports ranged from: theft of campus property ([a TV Sharp TV 70” was reported stolen in January 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-enero-2024.pdf)), to violence on campus grounds ([a student was thrown against a chair by another student in February 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/04/Informe-de-Actos-Delictivos-febrero-2024-eom.pdf)), to verbal harassment and threats ([a student reported that she was being threatened by an employee in april, 2024](https://www.uprm.edu/calidaddevida/wp-content/uploads/sites/11/2024/06/Informe-de-Actos-Delictivos-ABRIL-2024-.pdf)).
