### ISSUE TITLE
Documentation Feedback: Eliminating Duplicate Behaviors and Reworking Functions

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#377]
1. Eliminate Duplication in Behaviors Section

   Feedback: "There's some duplication below the new text on the behaviors."

   Task: Remove any duplicated text or content in the behaviors section to enhance clarity.

2. Integrate Function Signatures with Operations

   Feedback: "As I wrote in comment on the previous submission: function signatures should not go into a separate section. They describe important aspects of operations that should be there with the description of those operations."

   Task: Incorporate function signatures directly into the descriptions of their corresponding operations, rather than placing them in a separate section.

3. Revise Function Definitions and Data Handling

   Feedback: "Does the function reportSuspiciousActivity return, in the ReportConfirmation, a report? If so, then you surely there's something like a 'report book' or 'report registry', but then there would also have to be a function that takes a report and enters it into the report registry. If the report itself is not part of the ReportConfirmation, then the question is: how does the system record the reports? Where are they kept and how do they get there? Similarly, in your function sendSafetyAlert, if you want to send to all the users: where do you get the users from? How do you know which users the alert has already been sent to? You either need the return value to include some kind of alert object or you need to pass into the function some kind of alert registry that then also becomes part of the result (possible modified). If you take the first route you then need another function that serves the responsibility to add the alert to that alert registry. Go over all the functions here and review them."

   Task: Revisit all function definitions to clarify inputs, outputs, and data handling. Define how data is stored, retrieved, and modified (e.g., report registries, user lists, alert acknowledgments).

Deadline by end of Milestone 3.

**Comment by JorgeC08** [comment]
@lex939 

Hi Lex! Already implemented and removed redundancies per the professor feedback.

Added the function signatures with their explanation on the subsection 2.1.5, and the section 2.1.6 became redundant.

If there's anything else, let me know.
