### ISSUE TITLE
Documentation Feedback: Misplacement + Duplicates

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#378]
1. Reevaluate and Merge Overlapping Behaviors

    Feedback: "I think the reporting suspicious activity behavior and the real-time safety monitoring actually describe the same thing. Also, a behavior that you consists of only a single action and a single event is not a behavior: it's an action that triggers an event."

    Task: Review behaviors to identify and merge overlapping ones. Ensure each behavior represents a distinct and meaningful set of actions and events.

2. Remove Misplaced Function Signatures

    Feedback: "Why are the function signatures here where there are no functions/actions/operations?"

    Task: Remove function signatures from sections that do not contain related functions, actions, or operations, or add the necessary context to justify their presence.

3. Check for Duplication and Accuracy in Functions

    Feedback: "There's some duplication on page 41 e.g. concerning reportSuspiciousActivity."

    Task: Review all function signatures for duplication and accuracy. Ensure that each function is uniquely defined and that data flows are correctly represented.

Deadline by end of Milestone 3.

**Comment by YanehRuiz** [comment]
Duplicate issue of #377
