### ISSUE TITLE
Documentation Feedback: Clarify and Define Requirements

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#380]
1. Clarify System Performance Requirements

    Feedback: "'The system must be able to respond to user requests as fast as its current conditions allow it to.' This seems an empty requirement: 'able' and 'current conditions allow' are (at least mostly) synonymous. Or, if we look at it from a different perspective: if anyone says that the system is not responding fast enough, the developers can always say 'its current conditions do not allow it to respond any faster'."

    Task: Rewrite performance requirements to be specific, measurable, and testable, avoiding vague terms like "as fast as current conditions allow."

2. Define Scalability and User Capacity Requirements

    Feedback: "'The user must be able to support around 500 user accounts that are active at the same time (at least, during its early stages).' First of all, you most likely mean 'the system-to-be must be able to...' But even then 'active at the same time' can mean too many different things. An active account could be taken as one that has been registered within the last 3 months. But you might mean something else here, I'd guess something more about simultaneous use."

    Task: Clarify scalability requirements by specifying the number of simultaneous users, defining what "active" means, and considering peak usage scenarios based on statistical modeling.

Deadline by end of Milestone 3.

**Comment by JorgeC08** [comment]
@lex939 

Hi Lex! Already made the corresponding changes to the 2.2.5 section, something to notice is that someone already added some things at the end, the last 6 points that are on bright green. Those were kind of vague and didn't modify or "deleted" the one of the previous milestone resulting on duplicated text. Those could be safely remove since they were added in this milestone.

**Comment by evnd04** [comment]
@lex939  Whenever you can approve ill close.

**Comment by lex939** [comment]
@evnd04 ready to close
