### ISSUE TITLE
Documentation Feedback: Concept Analysis and Avoiding Single Action-Event Behaviors

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#383]
1. Expand Concept Analysis with Thought Processes

    Feedback: "What you present in the concept analysis section is rather a terminology than a concept analysis. In concept analysis or formation you document your thoughts about what concepts should be derived from the underlying rough sketch. The emphasis is not on the results (the terms), but instead on the thoughts and insights that you have when considering the rough sketch and why you think the concepts should be 'cut' a certain way. The outcome (the terms) then go into the terminology. Maybe you actually went through such thinking, but the way it's written I cannot see that."

    Task: Enrich the concept analysis section by documenting the reasoning and thought processes behind concept derivation, not just listing the terms.

2. Avoid Single Action-Event Behaviors

    Feedback: "Also, a behavior that you consists of only a single action and a single event is not a behavior: it's an action that triggers an event."

    Task: Modify behaviors to encompass more complex interactions rather than single action-event pairs, providing deeper insights into system functionalities.

Deadline by end of Milestone 3.

**Comment by misaelmercado1** [comment]
I made the corresponding modifications to the concept analysis
also i dont think behavior modification goes here.

**Comment by YanehRuiz** [comment]
@lex939

**Comment by lex939** [comment]
@misaelmercado1 Both parts of the issue are meant to be separate in the document for M3, but in the same GitHub issue.

Please specify where in the Google Doc for M3 did you make your changes 👍 thank you

**Comment by misaelmercado1** [comment]
ok then this should have been two separate issues , or separated into subtask because one thing is changing the concept analysis and the event behaviors. going to need more time to modify the events

**Comment by misaelmercado1** [comment]
@lex939 finished the single event behaviors part the respective changes were made on 2.1.5 and on 3.1
