### ISSUE TITLE
Documentation Feedback: Clarifying I/O

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#384]
1. Clarify Data Storage in Function Outputs

    Feedback: "If you say something like 'once the report is submitted', then where is it submitted to? Wherever that is, it changes through the submission and so must go into the function and must come out of the function (possibly changed)."

    Task: Clearly define where data is stored or submitted in function outputs, specifying databases, registries, or other storage mechanisms.

2. Specify Input/Output Relations in Functions

    Feedback: "The access emergency resources function is too broad. It's not clear what its input/output relation would have to be."

    Task: Define the input and output parameters for all functions, ensuring they are precise and understandable.

Deadline by end of Milestone 3.

**Comment by YanehRuiz** [comment]
Please remove the duplicate issue description; this part is already mentioned on another issue.

**Comment by lex939** [comment]
> Please remove the duplicate issue description; this part is already mentioned on another issue. 

Removed. Ready for approval.

**Comment by lex939** [comment]
Added new text under 2.1.6 and completed this issue. It is now ready to be closed. @YanehRuiz @evnd04
