### ISSUE TITLE
Documentation Feedback: Distinguishing and Implementing

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#385]
1. Distinguish Between Validated and Unvalidated Reports

    Feedback: "Wouldn't the report have to change? Wouldn't we have to be able to distinguish between a validated report and one that hadn't been validated yet? Then it might even be a good idea to distinguish the concepts: 'report' and 'validated report'."

    Task: Implement mechanisms to differentiate between validated and unvalidated reports, possibly introducing separate data structures or flags.

2. Implement Function to Add Alerts to Registry

    Feedback: "You either need the return value to include some kind of alert object or you need to pass into the function some kind of alert registry that then also becomes part of the result (possibly modified). If you take the first route, you then need another function that serves the responsibility to add the alert to that alert registry."

    Task: Create functions responsible for adding alerts to the alert registry, ensuring alerts are tracked and managed properly. Document this.

Deadline by end of Milestone 3.

**Comment by CaribbeanCool** [comment]
@lex939 @YanehRuiz @evnd04 Here is the documented feedback

A `validated` flag can be added to the data structure to differentiate between validated and unvalidated reports, enabling easy identification of a report’s status. Alternatively, separate collections can store validated and unvalidated reports, ensuring clear boundaries between the two types. For instance, the `Report` object might include fields like `id`, `content`, and `validated`, with functions designed to filter reports based on this status or to update a report’s validation status when needed. Additionally, a validation workflow function can be implemented to mark a report as validated, modifying the `validated` field to `true` for the corresponding report. 

For managing alerts, an alert registry can be introduced as a centralized data structure to store alert objects. These objects may include attributes like `id`, `content`, `severity`, and `timestamp`. A function to create alerts should return a complete alert object, which can then be passed to another function responsible for adding it to the registry. Alternatively, a single function can handle creation and addition by taking input parameters (e.g., `content` and `severity`), generating the alert, and appending it directly to the registry. This ensures all alerts are tracked systematically. To enhance clarity, the process should be documented, detailing the structure of alerts, the purpose of each function, and example workflows for adding alerts to the registry. These mechanisms work together to maintain a robust system for report validation and alert management, ensuring clear functionality and efficient operations.

**Comment by evnd04** [comment]
@lex939 Approve when available.

**Comment by lex939** [comment]
Will approve, but need @CaribbeanCool to place this text in the documentation and later comment on this issue as to where in the text he placed it.

**Comment by evnd04** [comment]
@CaribbeanCool

**Comment by CaribbeanCool** [comment]
@lex939 @evnd04 I added it under 2.5

**Comment by evnd04** [comment]
@lex939

**Comment by lex939** [comment]
@evnd04 ready to close :)
