### ISSUE TITLE
Documentation Feedback: Ensuring Consistency and Removing Ambiguity

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#387]
1. Ensure Consistency in Terminology and Definitions

    Feedback: "Some of the comments on the previous submission have still not been addressed."

    Task: Review and standardize terminology and definitions throughout the documentation to ensure consistency.

2. Remove Ambiguity in Requirements Language

    Feedback: "First of all, you most likely mean 'the system-to-be must be able...'."

    Task: Edit requirements to eliminate ambiguous language, ensuring that the subject (e.g., "the system-to-be") is correctly identified.

3. Provide Detailed Examples in Concept Analysis

    Feedback: "Maybe you actually went through such thinking, but the way it's written I cannot see that."

    Task: Include detailed examples and explanations in the concept analysis to illustrate the thought process behind concept derivation.

Deadline by end of Milestone 3.

**Comment by lex939** [comment]
Please specify what and where you added/modified/removed information in the Google Doc file to proceed with closing the issue.

**Comment by johnsantiago9** [comment]
Adjusted text to remove ambiguity and modify it to the correct terminology in parts(Domain Narrative, Part 2.1.5, Function Signatures, 2.2.1, Personas, Requirements, Implementation), I also identified correctly the subjects in the requirements,  Added examples in the concept analysis .

**Comment by lex939** [comment]
@YanehRuiz @evnd04 This issue is completed and ready to be closed.
