### ISSUE TITLE
Documentation Feedback: Avoiding Global State-Based Design

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#388]
Feedback: "While the context API solves the problem of prop drilling, it comes with the drawback of creating a global state-based design."

Task: Refactor the system design to prevent reliance on global states, promoting modularity and scalability. Document this.

Deadline by end of Milestone 3.

**Comment by diego-velez-upr** [comment]
This might need an additional task for the implementation, or are we going to focus on the documentation only? @YanehRuiz

**Comment by diego-velez-upr** [comment]
It seems as if we are focusing on the documentation, since I don't see where we are using the Context API as we mention it in the documentation.

**Comment by diego-velez-upr** [comment]
The full feedback is:

> While the context API solves the problem of prop drilling, it comes with the drawback of creating a global state-based design. Consider using higher-order components, using functions to assemble components from other components.

So, I think that we could use a factory pattern here as he suggested addressing the global state issue.

**Comment by diego-velez-upr** [comment]
The prop flow diagram and its description was updated in section `2.3.1 Selected Fragments of the Implementation`.
