### ISSUE TITLE
Documentation Feedback: Enhance and Specify

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#391]
1. Enhance Behaviors with Multiple Actions and Events

    Feedback: "I think the reporting suspicious activity behavior and the real-time safety monitoring actually describe the same thing. Also, a behavior that you consists of only a single action and a single event is not a behavior: it's an action that triggers an event."

    Task: Expand behaviors to include multiple actions and events, providing a richer representation of system interactions.

2.  Specify Data Structures for Registries

    Feedback: "You either need the return value to include some kind of alert object or you need to pass into the function some kind of alert registry."

    Task: Define the data structures used for registries like alerts and reports, and specify how functions interact with these structures.

Deadline by end of Milestone 3.

**Comment by diego-velez-upr** [comment]
The second point is incomplete, the quote is missing a lot of feedback. The full feedback related to the second quote is: 

> Does the function reportSuspiciousActivity return, in the ReportConfirmation, a report? If so, then you surely there's something like a "report book" or "report registry", but then there would also have to be a function that takes a report and enters it into the report registry. If the report itself is not part of the ReportConfirmation, then the question is: how does the system record the reports? Where are they kept and how do they get there? Similarly, in your function sendSafetyAlert, if you want to send to all the users: where do you get the users from? How do you know which users the alert has already been sent to? **You either need the return value to include some kind of alert object or you need to pass into the function some kind of alert registry** that then also becomes part of the result (possible modified). If you take the first route you then need another function that serves the responsibility to add the alert to that alert registry. Go over all the functions here and review them. Ask questions like, when an alert was acknowledged, will we need to distinguish an acknowledged alert from one that has not yet been acknowledged? How can we do so? What information needs to be in the acknowledgment? Do we need the alert itself in there or at least some reference? How about validation of reports: wouldn't the report have to change? Wouldn't we have to be able to distinguish between a validated report and one that hadn't been validated yet? Then it might even be a good idea to distinguish the concepts: "report" and "validated report". You can then state functions as taking "validated report" as parameters and (in a typed language) you can then no longer call such a function with a report that has not yet been validated. Assuming that there only one function, validateReport that can take a report and produce a validated report. The access emergency resources function is too broad. It's not clear what it's input/output relation would have to be.

@YanehRuiz I think this task could be split into two tasks.

**Comment by diego-velez-upr** [comment]
I addressed the first task. I think the professor was right, so I deleted the reporting suspicious activity, and changed some phrasing in the `Real-Time Safety Monitoring` section.

**Comment by diego-velez-upr** [comment]
For the second subtask, I don't think that we need to

> Define the data structures used for registries [...]

because the `ReportConfirmation` output of the (now) `submitIncidentReport` function signifies if the report was submitted successfully or not, thus his second point applies.

**Comment by diego-velez-upr** [comment]
I addressed the second issue, I renamed some input and output objects to have some consistency between the signatures. E.g. some were using `ReportDetails` and others `Report` but they seem like they should be the same object, so I renamed them to `Report`.

I also clarified some of his confusion by adding in the details that users are obtained from the database backend, that a report is sent to the database backend as "Pending" and that it only triggers when users create a report.

Not sure how the highlighting is supposed to work, if I'm supposed to mark it as yellow then change it separately as green. So I simply changed it and highlighted it as yellow on the spot.

**Comment by diego-velez-upr** [comment]
Do I need to add my changes to the documents change log or something?

**Comment by YanehRuiz** [comment]
Re-tagging @lex939

**Comment by lex939** [comment]
This issue is ready to close ☺️ @YanehRuiz
