### ISSUE TITLE
[Lecture Topic Task] Open/Closed Principle in Database Management Mechanisms

### ISSUE THREAD

**Issue by shenied-maldonado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#393]
### Objective
Document the consideration of the Open/Closed Principle in CRUD operation implementation. 

### Task Description
The Open/Closed Principle states that software entities should be open for extension but closed for modification. In other words, developers should be able to add new functionality without any necessary adjustments to the existing code. SafeRUM's data modeling and access objects were designed for easy inclusion of new operations with Flask's Blueprints for modular applications. Documentation should include mention of this as clean architecture design.  

### Implementation
Include explanation of the Open/Closed Principle incorporation into database communication mechanism design in SafeRUM documentation.

### Subtasks
N/A

### Testing and Debugging
N/A

### Deadline
Milestone 3

**Comment by YanehRuiz** [comment]
@lex939
