### ISSUE TITLE
[Lecture Topic Task] Intention-revealing interfaces for Report Creation page

### ISSUE THREAD

**Issue by NathBat09** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#411]
Objective:

The task aims to implement a function on the report creation page following the principles of intention-revealing interfaces and rewrite. This ensures that developers working on the system can clearly understand the purpose and function of the button and modal without needing to dig into their implementation.

Task Description:

The task involves adding a button labeled with a descriptive name, such as “Help” or “Learn More,” on the report creation page. When clicked, this button will call a function to open a modal that explains how to use the report creation page. The following principles will be applied:

Intention-Revealing Functions: Functions such as openHelpModal() and closeHelpModal() will be used to make the purpose of the operations clear.
Purpose-Driven Variables: Variables like isHelpModalVisible will be employed to manage the state of the modal, avoiding ambiguity.
Encapsulation: The logic for opening and closing the modal will be encapsulated within its own module or component, ensuring maintainability and clarity for other developers.

Implementation:

- Create a button element on the report creation page with a clear, descriptive label.
- Add a function openHelpModal() to handle the click event and display the modal.
- Implement closeHelpModal() to manage the closing of the modal, triggered by clicking a “Close” button or outside the modal area.
- Ensure the modal content is encapsulated within a dedicated component or module, exposing only necessary functionalities.
- Subtasks:

Deadline:

Milestone 3

**Comment by YanehRuiz** [comment]
This is for the Lecture Topic "Supple Design", correct?
