### ISSUE TITLE
[Lecture Topic Task] Developing a Ubiquitous Language for SafeRUM

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#416]
**Objective:**

Create a consistent and shared vocabulary (Ubiquitous Language) for the SafeRUM project, enhancing communication among team members and aligning the domain model with the project requirements.

---

**Task Description:**

The goal of this task is to develop a **Ubiquitous Language** that encapsulates key domain concepts within the SafeRUM project. By defining and documenting the terms, phrases, and language specific to the domain, the team can improve collaboration, reduce misunderstandings, and ensure that everyone has a shared understanding of the project's core elements.

Work to be done includes:

- **Identifying all important terms and concepts** used in the SafeRUM project.
- **Documenting the Ubiquitous Language** in a shared resource accessible to all team members.
- **Facilitate better communication** between developers and domain experts by using the agreed-upon language.

---

**Implementation:**

- **Identify Key Domain Terms:**
  - Review existing project documentation, user stories, and requirements to extract domain-specific terms.
  - Examples include: "Incident Report," "Real-Time Notification," "S.O.S Alert," "User," "Administrator," "Validation," "Aggregate," etc.

- **Document the Ubiquitous Language:**
  - Create a glossary or dictionary of terms with clear definitions.
  - Use collaborative tools (e.g., shared documents, wikis) for accessibility and easy updates.
  - Include context, usage examples, and any synonyms or related terms.

- **Promote Consistent Usage:**
  - Encourage all team members to use the Ubiquitous Language in their work.
  - Update existing documents, diagrams, and communication to reflect the agreed-upon language.
  - Integrate the language into modeling tools and code comments where appropriate.

---

**Subtasks:**

1. **Term Extraction:**
   - **Task Description:** Go through all project materials to list potential domain terms.
   - **Implementation Ideas:**
     - Assign team members to review specific documents.
     - Compile terms into a shared list.

2. **Glossary Creation:**
   - **Task Description:** Compile the terms and definitions into a formal document.
   - **Implementation Ideas:**
     - Use a standardized format for each entry.
     - Include sections for definitions, examples, and related terms.

3. **Dissemination:**
   - **Task Description:** Share the glossary with the entire team and integrate it into the project repository.
   - **Implementation Ideas:**
     - Announce the glossary via team communication channels.

4. **Application:**
   - **Task Description:** Ensure all team members use the Ubiquitous Language in their communication and documentation.
   - **Implementation Ideas:**
     - Encourage team leads to enforce usage.
     - Update templates and guidelines to include the Ubiquitous Language.

5. **Ongoing Maintenance:**
   - **Task Description:** Set up a process for updating the language as the project evolves.
   - **Implementation Ideas:**
     - Create a protocol for suggesting and approving changes.
     - Assign a curator or a small team responsible for maintaining the glossary.

---

**Testing and Debugging:**

- **Feedback Mechanism:**
  - Establish a channel (e.g., a dedicated email or Slack channel) for team members to provide feedback or suggest additions.
  - Hold periodic review meetings to address any issues.

- **Adjustments:**
  - Update the glossary based on practical usage and any misunderstandings that arise.
  - Ensure that changes are communicated promptly to the entire team.

---

**Deadline:** November 27, 2024

**Comment by evnd04** [comment]
Add description today or i will close this task, we do not allow placeholder tasks.

**Comment by joel-alvarado** [comment]
Document can be found [here](https://docs.google.com/document/d/1iFxyTigdXzqhlhHXQHZgTpp3uklGx225W9NCEyp0CVk/edit?usp=sharing).
