### ISSUE TITLE
[Lecture Topic Task] Documenting the Life Cycle of the Incident Reporting Process 

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#417]
Objective:
The objective of this task is to document the life cycle of a key process in the SafeRUM system. This includes breaking down the process into clear steps, identifying related actions and events, and creating a visual representation of the workflow to improve understanding and communication.

Task Description:
Select a core process in the SafeRUM application (e.g., "Incident Reporting" or "Alert Notifications").
Break down the process into sequential steps, describing actions taken by the user, system responses, and outcomes at each stage.
Create a diagram that illustrates the flow of the process.

Steps to Implement:

Select the Process:
Choose a process that is central to the system and already described in the project documentation.
Break Down the Process
Create a Workflow Diagram:
Use tools like Lucidchart, Draw.io, or even hand-drawn sketches to represent the process visually. 

Deliverables:

Process Description:
A list of clear and detailed steps in the selected process.

Workflow Diagram:
A visual representation of the process lifecycle.

Deadline:
Complete this task by November 26, 2024, at 23:00 hours.

**Comment by evnd04** [comment]
Add description today or i will close this task, we do not allow placeholder tasks.

**Comment by JuanJRivera** [comment]
This task is based on the topic "The Life Cycle of a Domain Object" from the course. @lex939  @shenied-maldonado


I noticed that there is a task with a similar name(Issue#424) after creating the task, but it only covers one area. I would like to apply the same method to cover additional areas and create a diagram with the information. Is it possible to continue with this task?

**Comment by JuanJRivera** [comment]
This task is based on the topic "The Life Cycle of a Domain Object" from the course. @lex939 @shenied-maldonado

I noticed that there is a task with a similar name(Issue#424) after creating the task, but it only covers one area. I would like to apply the same method to cover additional areas and create a diagram with the information. Is it possible to continue with this task?

**Comment by shenied-maldonado** [comment]
> This task is based on the topic "The Life Cycle of a Domain Object" from the course. @lex939 @shenied-maldonado
> 
> I noticed that there is a task with a similar name(Issue#424) after creating the task, but it only covers one area. I would like to apply the same method to cover additional areas and create a diagram with the information. Is it possible to continue with this task?

It seems reasonable enough to me to have two separate issues for two separate processes. #424 focuses on the user account lifecycle whereas you'll be geared towards the reporting process. 

I'll leave the ultimate decision up to @lex939

**Comment by JuanJRivera** [comment]
on 2.3.1 seccion managment
