### ISSUE TITLE
[Lecture Topic Task] Identifying and Documenting Core Domain Concepts 

### ISSUE THREAD

**Issue by JuanJRivera** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#418]
Objective:
The objective of this task is to identify the core domain concepts in SafeRUM, document their relationships, and ensure they are well-defined to enhance understanding and communication within the development team.

Task Description:
Review the SafeRUM project documentation to identify the core domain concepts.
Create a list of these concepts and provide clear definitions for each.
Visualize the relationships between these concepts in a simple diagram.

Implementation Steps:

Identify Core Concepts:

Examples of core concepts in SafeRUM might include:
User: Represents individuals interacting with the system.
Report: Represents an incident or suspicious activity.
Notification: Represents messages sent to users or security personnel.
Role: Represents user roles such as Admin, Security, or General User.
Define Each Concept:

Provide a brief definition for each concept. For example:
User: A person who interacts with the system, identified by unique credentials.
Report: A record of a suspicious activity submitted by a user.
Notification: A message generated by the system to inform users about important events.
Document Relationships:
Identify how these concepts relate to each other. For example:
A User creates a Report.
A Notification is sent to a User based on the Role.

Create a Visual Representation:
Draw a simple diagram showing these concepts and their relationships.

Deliverables:
List of Core Concepts:
Definitions of the key domain objects.
Concept Relationship Diagram:
A simple diagram illustrating the relationships between domain concepts.

Deadline:
Complete this task by November 26, 2024, at 23:00 hours.

**Comment by evnd04** [comment]
Add description today or i will close this task, we do not allow placeholder tasks.

**Comment by JuanJRivera** [comment]
This task aligns with the topic "Domain Model and Ubiquitous Language" @lex939 @shenied-maldonado

**Comment by JuanJRivera** [comment]
on 2.3.1 seccion managment
