### ISSUE TITLE
Document Flask Endpoints Using Flask-Autodoc

### ISSUE THREAD

**Issue by joel-alvarado** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#420]
**Objective:**

Create comprehensive and up-to-date documentation for all Flask endpoints in the SafeRUM project using the Flask-Autodoc extension. This will enhance code maintainability, facilitate onboarding of new developers, and provide clear API references for internal and external stakeholders.

---

**Task Description:**

The goal of this task is to generate detailed documentation for the Flask-based backend API endpoints of the SafeRUM project using Flask-Autodoc. The documentation should cover all aspects of each endpoint, including their purpose, URL routes, HTTP methods, parameters, request and response schemas, authentication requirements, and examples. This documentation will be integrated into the project's existing documentation structure and made easily accessible to the development team and other stakeholders.

**Work to be done includes:**

- Installing and configuring Flask-Autodoc in the project.
- Annotating all Flask endpoint functions with detailed docstrings.
- Decorating endpoint functions with the `@auto.doc()` decorator provided by Flask-Autodoc.
- Generating HTML documentation from the annotated code using Flask-Autodoc.

---

**Implementation:**

1. **Install and Configure Flask-Autodoc:**

   - Install Flask-Autodoc using the project's package manager.
   - Import Flask-Autodoc in the Flask application and initialize it.
   - Update the application's configuration if necessary to integrate Flask-Autodoc.

2. **Annotate Flask Endpoints:**

   - Go through each Flask endpoint and add the `@auto.doc()` decorator.
   - Add or update docstrings for each endpoint, ensuring they include:

     - A brief summary of the endpoint's purpose.
     - URL route and allowed HTTP methods.
     - Parameters and data types (query parameters, path variables, request body).
     - Request and response schemas, including expected input and output formats.
     - Authentication and authorization requirements.
     - Possible error responses with status codes and messages.
     - Examples of requests and responses for clarity.

3. **Generate Documentation:**

   - Create a route in the Flask application that generates and serves the documentation using Flask-Autodoc.
   - Access the generated documentation via a web browser to review its content and layout.

4. **Review and Refine Documentation:**

   - Proofread the generated documentation for accuracy, clarity, and completeness.
   - Adjust formatting and content in docstrings as necessary to improve readability and consistency.
   - Ensure that all endpoints are properly documented and that the information is up-to-date.

---

**Subtasks:**

1. **Install and Configure Flask-Autodoc:**

   - Install the Flask-Autodoc package.
   - Import and initialize Flask-Autodoc in the Flask application.
   - Verify that Flask-Autodoc is correctly set up and ready to use.

2. **Annotate Flask Endpoints:**

   - Decorate each Flask endpoint with the `@auto.doc()` decorator.
   - Write comprehensive docstrings for each endpoint, following the agreed-upon style guidelines.
   - Ensure that all necessary information is included in the docstrings.

3. **Generate and Review Documentation:**

   - Implement the documentation generation route in the Flask application.
   - Generate the documentation and access it through a web browser.
   - Review the documentation for completeness and correctness.

4. **Automate Documentation Generation:**

   - Set up scripts or integrate tools to automate the generation of documentation as part of the development process.
   - Ensure that the documentation stays up-to-date with the codebase.

---

**Testing and Debugging:**

- **Verification of Endpoint Coverage:**

  - Cross-reference the list of Flask endpoints with the generated documentation to ensure all endpoints are documented.
  - Confirm that newly added endpoints are automatically included in the documentation.

- **Content Review:**

  - Have team members review the documentation for clarity, accuracy, and usefulness.
  - Collect feedback on any missing information or areas that need improvement.
  - Make necessary adjustments based on the feedback received.

---

**Deadline:** November 27, 2024

**Comment by evnd04** [comment]
Add description today or i will close this task, we do not allow placeholder tasks.
