### ISSUE TITLE
[Lecture Topic Task] The Life Cycle of a Domain Object for User Account & Sessions

### ISSUE THREAD

**Issue by williammartinez10** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#424]
Objective:

Map and document the lifecycle of user accounts and sessions to improve clarity and maintainability.

Task Description:

This task involves detailing the stages of a user account and its session lifecycle. It includes the creation, modification, session activity, recovery, and deletion phases. The goal is to ensure smooth transitions between states and robust management of user sessions.

Implementation:

* Create a written document or flowchart visualizing the user and session lifecycle.
* Identify key triggers and transitions, such as login, logout, and session expiration.
* Ensure the lifecycle supports common user scenarios (e.g., password resets, account updates).

Subtasks:

* Define each stage in the user lifecycle.
* Identify session management operations, such as token issuance and expiry.
* Document transitions, including triggers and outcomes.

Testing and Debugging:

* Simulate various scenarios (e.g., password reset, simultaneous logins) to validate the lifecycle design.

Deadline:

Should be completed by the end of Milestone 3.

**Comment by williammartinez10** [comment]
@evnd04 @YanehRuiz

**Comment by williammartinez10** [comment]
https://docs.google.com/document/d/1g9apsceWdcXE9SZGtjw3fmhTCLSSMWv_slLWWT6ShYM/edit?tab=t.0

**Comment by williammartinez10** [comment]
@lex939 I am not sure where this can be placed in the documentation, any suggestions?

**Comment by williammartinez10** [comment]
Added to 2.3.1

**Comment by williammartinez10** [comment]
Difficulty and urgency are missing for this issue

**Comment by YanehRuiz** [comment]
> Difficulty and urgency are missing for this issue

It's been added! Closing now!
