### ISSUE TITLE
[Lecture Topic Task] Designing the Identity Operation for User Account & Sessions

### ISSUE THREAD

**Issue by williammartinez10** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#425]
Objective:

Ensure every user account has a unique identity in the system to maintain data integrity and avoid conflicts.

Task Description:

This task involves documenting and validating the mechanisms used to ensure unique identities for users. It includes verifying email addresses during registration, checking for duplicates, and maintaining unique identifiers during operations like login and password resets.

Implementation:

* Identify all points in the system where user identities are created or verified (e.g., signup, login).
* Document the steps taken to prevent duplication, such as email validation and database checks.

Subtasks:

* Review and document current email validation methods.
* Test for duplicates in the registration process.
* Verify that unique identifiers like email or session tokens are consistently used.

Testing and Debugging:

* Test scenarios with duplicate emails or conflicting accounts to ensure proper error handling.

Deadline:

Should be completed by the end of Milestone 3.

**Comment by williammartinez10** [comment]
@evnd04 @YanehRuiz

**Comment by williammartinez10** [comment]
https://docs.google.com/document/d/1ICiQ_GPHkUtqShuk3TRfvbWzwz9e4qJD6BxpNtye5ak/edit?tab=t.0

**Comment by williammartinez10** [comment]
#424 and #426 contain similar information to the one in this document, they have been added to the documentation

**Comment by williammartinez10** [comment]
Difficulty and urgency are missing for this issue

**Comment by YanehRuiz** [comment]
> Difficulty and urgency are missing for this issue

Its been addressed, closing now!
