### ISSUE TITLE
[Lecture Topic Task]: Defining and Documenting Safety Data Models 

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#427]
Objective:
Given that different teams may make changes independently, it is essential to define the purpose and structure of each model in the safety status reporting system to ensure consistent understanding and usage of terminology across all teams.

Task Description:

Document the purpose and structure of each model used in the system.
Example models: Location, Safety Level, Incident Records.
Include attributes, relationships, and roles for each model.
Provide an explanation of how these models interact to create the final safety status map.
The documentation should be detailed enough for teams to use as a reference for further development.
Testing and Debugging:

Review the documentation with the project leader or documentation leader to ensure it meets established criteria for clarity, completeness, and usability.
Incorporate feedback to improve the documentation if necessary.
Deadline:
Milestone 3

**Comment by Jjulianirizarry24** [comment]
@lex939
