### ISSUE TITLE
[Lecture Topic Task]: Creating a Data Structure for Safety Status Reporting 

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#428]
Objective:
Define and implement a basic data structure to store and manage safety-related information for locations effectively.

Task Description:

Design a simple data structure to represent:

Location: Name, coordinates, region.
Safety Level: Safe, moderate, unsafe.
Incidents: Type of incident (e.g., theft, fire), date, and severity.
Write a description or create a small code snippet (in a programming language of your choice) to implement this structure.

Testing and Debugging:

Validate the structure by creating 2-3 example entries (e.g., a location with a moderate safety level and a list of incidents).
Check with the documentation leader or project lead to confirm that the structure meets requirements.
Deadline:
Milestone 3, End of September 26

**Comment by YanehRuiz** [comment]
This issue is the same as #427

**Comment by lex939** [comment]
This should be closed as duplicate @YanehRuiz
