### ISSUE TITLE
User Profile Management Schematic Design Using Figma

### ISSUE THREAD

**Issue by noel-vargas** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#43]
Objective:
Create a schematic to visualize the structure and layout of the user profile management page, focusing on user interaction and functionality.

Task Description:
The profile management page allows users to update their personal information, upload a profile picture, and change their password. This task focuses on designing an intuitive and user-friendly interface. The schematic should provide a visual representation of the page components and user flow.

Implementation:
This task requires the creation of wireframes or mockups for the user profile management page. The schematic should focus on the layout of input fields, buttons, error handling, and success messaging. Tools like Figma or Miro are encouraged to design the schematic. 

Subtasks:

UI/UX Research: Research best practices for profile management pages to ensure optimal user experience.
Wireframe Creation: Create a wireframe of the profile management page, outlining the placement of input fields, labels, profile picture upload, and buttons.
Error Handling and Feedback: Design how validation errors, success messages, and user feedback will be displayed within the UI.
Feedback and Iteration: Gather feedback from team members to refine the design before moving to the high-fidelity mockup stage.

Testing and Debugging:
Final review and approval will come from the team leader and managers. Continuous feedback from stakeholders and users is encouraged to ensure the design is intuitive and user-friendly.

Milestone:
The wireframe and schematic design should be completed and reviewed by September 15th, 2024.
https://www.figma.com/design/VdsIsr8i5rQYLW2SCdzqiL/Profile-Management-Page-Design?node-id=0-1&t=5gjnNB00PwWtc3Oo-1

**Comment by evnd04** [comment]
Add this to the joint figma task, as in paste the link into that issue so @yadrielsamir could join it with the other designs.
