### ISSUE TITLE
[Lecture Topic Task] Identify and document the core domain for SafeRum that delivers the highest value

### ISSUE THREAD

**Issue by misaelmercado1** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#433]
Objective:

This task objective is to identify and document the core domain for saferum that delivers the highest value for our project.

Task Description:

This task stems from the Strategic Design lecture , this task aims to identify the core domain that delivers the highest impact for our project in other words , what are the key concepts we need sou we get maximum value for our project

Implementation:

This would just be a documentation task
Deadline:

Milestone 3

**Comment by Jjulianirizarry24** [comment]
@lex939

**Comment by misaelmercado1** [comment]
@lex939

**Comment by misaelmercado1** [comment]
https://docs.google.com/document/d/1nSTduiBd1s23SHQeMmXAUaSF3u_x2KgevMLX8Zpej-Q/edit?usp=sharing
