### ISSUE TITLE
[Lecture Topic Task] Refactor Report Creation to Comply with Declarative Design Principles

### ISSUE THREAD

**Issue by jonVargas1** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#442]
Objective:
Refactor ReportCreation.tsx to adhere to the declarative design principle, enhancing code readability, reusability, and maintainability. The refactored code will make the component easier to extend and debug by modularizing logic and UI elements.

Task Description:
The goal of this task is to refactor the existing code to adhere to declarative design principles, making it more modular, readable, and maintainable. By breaking the code into reusable components, simplifying state management, and abstracting logic into functions, it will become cleaner and easier to modify. 

Implementation:
- Create modular components, improving code reusability and reducing duplication.
- Separate different rendering conditions into distinct helper functions to keep the main render logic clean and declarative.
- Centralize common state management logic to ensure that functionality is reused consistently across the component.

Testing and Debugging:
Test the refactored components to ensure they work as expected.

Deadline:
Milestone 3

from _Supple Design, slide 52_

**Comment by jonVargas1** [comment]
@YanehRuiz @evnd04

**Comment by YanehRuiz** [comment]
Just checking: Is this intended to be a LTT?  If so, please rename it so the script can read it. If not, it seems ready for approval!

**Comment by jonVargas1** [comment]
didn't notice that. thanks for letting me know

**Comment by YanehRuiz** [comment]
Please add the completed tags here as well when you're done!
