### ISSUE TITLE
[Lecture Topic Task]  Declarative design

### ISSUE THREAD

**Issue by YanehRuiz** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#451]
Objective:
Provide concise documentation explaining the declarative design principles applied in the project.

Task Description:
Create a brief document that outlines how declarative design is utilized within the project, highlighting key concepts and their practical implementation.

Implementation:
Summarize the core principles of declarative design relevant to our work and describe their application in the project in a clear and accessible manner.

Testing and Debugging:
Review the documentation for clarity and accuracy to ensure it effectively communicates the intended information.

Deadline:
Milestone 3

**Comment by lex939** [comment]
This was placed in Section 0 of the document. This issue is ready to close.
