### ISSUE TITLE
Add 2.2.5 Machine Requirements

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#82]
Objective:
Define and document the machine requirements that specify the technical and performance aspects the system must meet. These requirements ensure that the system is reliable, efficient, and capable of handling expected workloads and operating conditions.

Task Description:
The Machine Requirements section focuses on the technical specifications and constraints that the system must satisfy to ensure smooth operation. This includes performance metrics (e.g., response time, throughput), hardware and software dependencies, scalability, reliability, and availability. These requirements are crucial for ensuring the system performs well under expected and, if necessary, unexpected load conditions, and meets the technical expectations of stakeholders.

Implementation:
	1.	Identify the key technical and performance needs of the system, including hardware, software, network, and operational requirements.
	2.	Document the machine requirements, including specific metrics for performance, reliability, scalability, and availability.
	3.	Ensure that the machine requirements are measurable and testable, allowing for verification during development.
	4.	Continuously refine the machine requirements as the project progresses and new technical challenges are identified.

Subtasks:
	•	Performance Requirements: Define specific performance criteria (e.g., response times, load handling, maximum number of concurrent users) that the system must meet.
	•	Hardware and Software Dependencies: Document the hardware and software environment the system will need to operate within, including server requirements, operating systems, and external libraries.
	•	Reliability and Availability: Define requirements for system uptime, redundancy, failover mechanisms, and acceptable downtime windows.
	•	Scalability Requirements: Define how the system will scale to handle increased usage, including plans for horizontal and vertical scaling, load balancing, and resource allocation.
	•	Review for Completeness: Ensure that all critical machine requirements are documented and cover performance, reliability, and scalability aspects.
	•	Iterative Refinement: Plan for ongoing updates to machine requirements as the project evolves and as more information is gathered on performance needs.

Testing and Debugging:
	•	Review the machine requirements with team members and stakeholders to ensure they align with the technical needs of the system.
	•	Validate that the requirements are measurable and can be tested during the development and deployment phases.
	•	Test for completeness by ensuring that all critical aspects of system performance, scalability, reliability, and dependencies are addressed.

Deadline:
Wednesday, September 18 at 11:59 p.m.

**Comment by Chosen-Juan1** [comment]
> A small fix is needed: there's a typo in "the user must be able to support around 500 user accounts." Change "IOS" to "iOS," and add a disclaimer stating that the system will be fully operational only while the user is connected to the internet; otherwise, the system won't connect, and access will be unavailable.
> 
> Aside from that, it's good to go! @Chosen-Juan1

Fixed the typo and added the disclaimer as a sub-requirement.
