### ISSUE TITLE
Add 0.8 Versioning

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#84]
Objective:
The objective of this task is to implement a “Versioning” section within the documentation to help users understand how different versions of the project are managed. This section will provide clarity on the versioning system used (e.g., Semantic Versioning) and how version numbers reflect changes in the project (e.g., major, minor, patch updates). This will ensure users and contributors are informed about updates, backwards compatibility, and how to follow the project’s development over time.

Task Description:
The “Versioning” section will detail the specific versioning scheme that the project follows, how updates and changes are tracked, and how users can reference older versions if necessary. This will be critical for contributors to understand how to label new releases and for users to know what updates are relevant for their needs.

The task involves:

	•	Researching and defining the versioning system (Semantic Versioning is recommended).
	•	Describing what each version number represents (e.g., major = breaking changes, minor = new features, patch = bug fixes).
	•	Including examples of previous project releases to demonstrate how versioning works in practice.
	•	Outlining the process for updating the version number with each new release or change to the project.

Implementation:

	•	Research and confirm whether Semantic Versioning or another system will be used.
	•	Write a clear description of how the versioning system is applied within the project.
	•	Include a table or timeline of previous versions and their associated changes (if applicable).
	•	Provide instructions on how contributors should update version numbers when creating pull requests or releases.
	•	Add links to external resources (such as semver.org) to offer further context.

Subtasks:

	1.	Research and Define Versioning System:
	•	Confirm which versioning system to use (e.g., Semantic Versioning).
	•	Write a short explanation of how the system works.
	2.	Document Version Number Changes:
	•	Create a section that explains how and when to increment version numbers.
	•	Include examples for each type of version change (e.g., major, minor, patch).
	3.	Create Release History Section:
	•	Add a timeline or table summarizing past releases and what changes were made in each version (if relevant).
	4.	Update Contribution Guidelines (if necessary):
	•	Ensure contributors understand how to manage version numbers during code changes or releases.

Testing and Debugging:

	•	Review: Once implemented, have a peer review the section to ensure clarity and correctness.
	•	Validation: Check whether the versioning explanation accurately aligns with the actual version control practices in use.
	•	Debugging: If the versioning system is not fully understood by testers or leads to confusion, iterate on the description and improve the explanation.

Deadline:
Friday, September 20, 2024, at 11:00 AM

**Comment by CaribbeanCool** [comment]
this issue is ready to be closed

**Comment by lex939** [comment]
@YanehRuiz @evnd04 Section 0.8 "Versioning" has been added to the documentation for M1. This issue is ready to be closed.
