### ISSUE TITLE
Add 2.3 Implementation

### ISSUE THREAD

**Issue by lex939** [uprm-inso4116-2024-2025-s1/semester-project-SafeRUM#85]
Objective:
Plan and document the implementation phase of the project, ensuring that the system’s architecture, design, and codebase are developed in alignment with the domain requirements and system specifications. This task will guide the development process and provide a roadmap for building the system.

Task Description:
The Implementation section outlines the steps required to build the system, covering aspects such as software architecture, component design, coding, and integration. This task includes developing the system based on the previously defined requirements, ensuring that all technical and functional aspects are covered. The implementation plan should also consider modular development, ensuring components are built in a way that can be tested and integrated efficiently.

Implementation:
	1.	Design the software architecture, identifying key components, modules, and their interactions.
	2.	Develop detailed component designs, specifying how each component will function and interact with others.
	3.	Write and test the codebase, ensuring that each component is developed according to the specifications.
	4.	Integrate components to form a complete system, conducting tests to ensure functionality and stability.
	5.	Continuously refine and update the implementation plan as the project progresses, addressing any technical challenges or changes in requirements.

Subtasks:
	•	Software Architecture Design: Define the high-level structure of the system, specifying components, modules, and their relationships.
	•	Component Design: Develop detailed designs for individual components, outlining their functionality, inputs, outputs, and interactions.
	•	Code Development: Write the code for each component, following best practices for modularity, scalability, and maintainability.
	•	Unit and Integration Testing: Conduct unit tests for individual components and integration tests to ensure all parts of the system work together as expected.
	•	System Integration: Integrate all components into a complete system, ensuring that the final product meets the domain and technical requirements.
	•	Refinement and Updates: Continuously update the implementation plan as new requirements, technical challenges, or optimizations arise.

Testing and Debugging:
	•	Perform unit testing for individual components to ensure they function correctly in isolation.
	•	Conduct integration testing to verify that components interact properly and that the system functions as a whole.
	•	Debug any issues that arise during the coding or integration phases, refining components as necessary.
	•	Validate the implementation with stakeholders to ensure it aligns with the original requirements and expectations.

Deadline:
Wednesday, September 18 at 11:59 p.m.

**Comment by diego-velez-upr** [comment]
I'm pretty sure this is completed. Requesting documentation review to ensure it complies with the guidelines established.

**Comment by YanehRuiz** [comment]
> I'm pretty sure this is completed. Requesting documentation review to ensure it complies with the guidelines established.

Since you mentioned the other components, could you please add the designs to the document? It would be great if you could briefly go over them, just like you did with the report and user profile pages.

**Comment by diego-velez-upr** [comment]
> > I'm pretty sure this is completed. Requesting documentation review to ensure it complies with the guidelines established.
> 
> Since you mentioned the other components, could you please add the designs to the document? It would be great if you could briefly go over them, just like you did with the report and user profile pages.

Not sure what other components you want me to add to the document, but I added the report creation UI to it.

**Comment by YanehRuiz** [comment]
It looks like you’ve already included those, so that’s great! The admin designs can be found in the following issues: #153, #45, and #49. You might also check #137, as it should have them included as well.

**Comment by diego-velez-upr** [comment]
Done, added the admin's setting page.
